// ============================================================
//  BANCO.JS — Questões extras (300+) para o Simulado DETRAN Pro
//  Categorias: sinalizacao, legislacao, direcao, infrações, seguranca, mecanica
// ============================================================

const BANCO_EXTRA = [

// ════════════════════════════════════════════════
//  SINALIZAÇÃO (60 questões)
// ════════════════════════════════════════════════
{p:"Placa com triângulo amarelo e figura de criança indica:",o:["Proibido crianças","Área escolar — velocidade máxima 30 km/h","Parque infantil à esquerda","Escola fechada"],c:1,cat:"sinalizacao",ex:"A placa A-17 (Área Escolar) alerta para a presença de crianças e impõe velocidade máxima de 30 km/h."},
{p:"O que significa a placa com círculo azul e seta apontando para frente?",o:["Proibido seguir em frente","Sentido obrigatório — frente","Via sem saída","Pista expressa"],c:1,cat:"sinalizacao",ex:"R-24a: círculo azul com seta = sentido obrigatório. Diferente da proibição (borda vermelha)."},
{p:"A placa R-5a (círculo com letra P riscada por uma linha diagonal) indica:",o:["Proibido parar e estacionar","Proibido apenas estacionar — parar brevemente é permitido","Estacionamento permitido","Proibido apenas para caminhões"],c:1,cat:"sinalizacao",ex:"Um risco = proibido ESTACIONAR. Parar rapidamente para embarque/desembarque ainda é permitido."},
{p:"Qual é a cor do fundo das placas de advertência?",o:["Branco","Azul","Amarelo","Verde"],c:2,cat:"sinalizacao",ex:"Placas de advertência (grupo A) têm fundo amarelo e bordas pretas, em formato triangular."},
{p:"A linha dupla contínua amarela no centro da pista indica:",o:["Pode ultrapassar nos dois sentidos","Proibido ultrapassar nos dois sentidos","Apenas veículos pesados não podem ultrapassar","Fim de pista dupla"],c:1,cat:"sinalizacao",ex:"Dupla linha contínua amarela = proibição absoluta de ultrapassagem para ambos os sentidos."},
{p:"Placa octogonal vermelha com a palavra 'PARE' obriga:",o:["Reduzir para 30 km/h","Parada total obrigatória antes da linha de retenção","Dar preferência ao tráfego da direita","Acionar o pisca-alerta"],c:1,cat:"sinalizacao",ex:"R-1: parada obrigatória — o veículo deve parar completamente, mesmo sem outros veículos."},
{p:"O que indicam as setas pintadas no chão da pista?",o:["Sugestão de direção","Sentido obrigatório de circulação na faixa","Faixa de ultrapassagem","Área de estacionamento"],c:1,cat:"sinalizacao",ex:"Marcas no pavimento (setas) indicam o sentido obrigatório de circulação naquela faixa."},
{p:"Uma placa com fundo verde indica geralmente:",o:["Proibição","Advertência de perigo","Rodovias e orientação de percurso","Informação de serviços"],c:2,cat:"sinalizacao",ex:"Fundo verde = placas de orientação de destino em rodovias (distâncias, localidades)."},
{p:"A linha branca contínua longitudinal na borda direita da pista indica:",o:["Borda do acostamento","Faixa de pedestres","Proibido mudar de faixa","Área de obras"],c:0,cat:"sinalizacao",ex:"Linha branca contínua na borda = delimitação do acostamento, proibido circular sobre ela."},
{p:"O que significa a placa com um triângulo invertido com borda vermelha?",o:["Pare obrigatório","Dê a preferência","Redução de velocidade","Proibido avançar"],c:1,cat:"sinalizacao",ex:"R-3 (Dê a Preferência): triângulo invertido, borda vermelha — reduza e ceda passagem."},
{p:"Placa circular azul com uma bicicleta branca indica:",o:["Proibido bicicletas","Via exclusiva para bicicletas — ciclovia","Atenção a ciclistas","Estacionamento de bicicletas"],c:1,cat:"sinalizacao",ex:"Círculo azul = obrigação. Bicicleta branca = via exclusiva para ciclistas (ciclovia)."},
{p:"A placa com o número '110' em círculo branco com borda vermelha indica:",o:["Distância de 110 metros","Velocidade mínima de 110 km/h","Velocidade máxima de 110 km/h","Proibido para veículos acima de 110 km/h"],c:2,cat:"sinalizacao",ex:"Círculo branco com borda vermelha e número = velocidade máxima. No caso, 110 km/h."},
{p:"Uma linha tracejada branca entre faixas permite:",o:["Ultrapassagem apenas à direita","Mudança de faixa com segurança","Parar em emergências","Ciclistas circularem"],c:1,cat:"sinalizacao",ex:"Linha tracejada branca longitudinal: pode mudar de faixa quando seguro."},
{p:"A marca 'PARE' pintada no asfalto indica:",o:["Sugestão de parada","Linha de retenção — parada obrigatória","Faixa de pedestres","Fim de rodovia"],c:1,cat:"sinalizacao",ex:"A palavra PARE no pavimento reforça a placa R-1, indicando onde o veículo deve parar completamente."},
{p:"Sinalização horizontal amarela no pavimento é utilizada:",o:["Apenas em aeroportos","Apenas em rodovias","Para separar fluxos opostos e em locais com restrições","Somente em estacionamentos"],c:2,cat:"sinalizacao",ex:"Amarelo = separação de sentidos opostos de tráfego e áreas com restrições especiais."},
{p:"O que indica a placa com fundo laranja?",o:["Obras permanentes","Sinalização temporária de obras ou situações especiais","Proibição em área de lazer","Rodovia pedagiada"],c:1,cat:"sinalizacao",ex:"Laranja = sinalização temporária. Deve ser obedecida com a mesma força legal das placas definitivas."},
{p:"Uma placa com triângulo amarelo e símbolo de exclamação (!) indica:",o:["Perigo específico","Perigo não especificado — verifique placa complementar","Obras à frente","Cruzamento próximo"],c:1,cat:"sinalizacao",ex:"A placa de 'Silhueta de Perigo' com ! é genérica. Geralmente acompanhada de placa auxiliar informando o tipo de perigo."},
{p:"Qual placa indica que há uma rotatória à frente?",o:["Triângulo amarelo com setas circulares","Círculo azul com setas circulares","Quadrado verde com setas","Retângulo azul com setas"],c:0,cat:"sinalizacao",ex:"A placa A-8 (Rotatória) é triangular amarela com símbolo de setas circulares."},
{p:"O que significa a placa com faixa branca horizontal sobre fundo vermelho?",o:["Velocidade máxima","Proibido entrar — sentido proibido","Pare obrigatório","Fim de proibição"],c:1,cat:"sinalizacao",ex:"R-2 (Sentido Proibido): fundo vermelho com faixa branca horizontal — proibida a entrada no sentido indicado."},
{p:"A placa que indica 'Velocidade Mínima' tem:",o:["Círculo branco com borda vermelha","Círculo azul com dois círculos concêntricos e número","Triângulo amarelo com número","Retângulo azul com número"],c:1,cat:"sinalizacao",ex:"R-7: círculo azul com número branco (às vezes dois arcos concêntricos) — indica velocidade mínima obrigatória."},
{p:"Tachões refletivos no meio da pista servem para:",o:["Decoração","Demarcar acostamento","Separar faixas e orientar o condutor à noite","Marcar vagas de estacionamento"],c:2,cat:"sinalizacao",ex:"Tachões (olhos de gato) refletem a luz dos faróis, auxiliando a percepção das faixas à noite."},
{p:"A placa R-6b (círculo com número 40) significa:",o:["Velocidade mínima 40","Velocidade máxima 40 km/h","Distância de 40 metros","40 quilômetros até o próximo pedágio"],c:1,cat:"sinalizacao",ex:"Círculo branco com borda vermelha e número 40 = velocidade máxima de 40 km/h."},
{p:"Onde é obrigatório colocar o triângulo de segurança após pane em rodovia?",o:["10 m à frente do veículo","30 m atrás do veículo","50 m à frente do veículo","No teto do carro"],c:1,cat:"sinalizacao",ex:"O triângulo deve ser colocado 30 metros atrás do veículo parado em rodovias."},
{p:"A placa com 'P' e dois riscos em X significa:",o:["Estacionamento tarifado","Proibido apenas estacionar","Proibido parar E estacionar","Estacionamento rotativo"],c:2,cat:"sinalizacao",ex:"R-5b: dois riscos = proibido tanto parar quanto estacionar. Mais restritiva que a de apenas um risco."},
{p:"Seta com ponta dupla pintada na pista indica:",o:["Pode ultrapassar em ambos os sentidos","Compartilhamento de faixa","Proibido ultrapassar","Faixa de retorno"],c:1,cat:"sinalizacao",ex:"Seta dupla = faixa compartilhada por veículos em dois sentidos ou por diferentes modais."},
{p:"O que indica a placa A-12 (triângulo com seta apontando para baixo)?",o:["Descida acentuada","Depressão (buraco) na pista","Mergulho em rio","Saída de emergência"],c:1,cat:"sinalizacao",ex:"A-12 (Depressão): triângulo amarelo com seta em V — depressão ou afundamento na pista à frente."},
{p:"Placa com símbolo de trem e triângulo amarelo indica:",o:["Estação de trem à direita","Passagem de nível com ou sem cancela à frente","Área de manobra de trem","Parada de metrô"],c:1,cat:"sinalizacao",ex:"As placas A-14 e A-15 advertem sobre passagem de nível com cancela ou sem cancela."},
{p:"A cor branca das marcas no pavimento é usada principalmente para:",o:["Separar sentidos opostos","Organizar tráfego no mesmo sentido e bordas da pista","Indicar obras","Faixas de ônibus"],c:1,cat:"sinalizacao",ex:"Branco = mesmo sentido de tráfego. Amarelo = sentidos opostos."},
{p:"Uma placa com círculo vermelho e silhueta de caminhão riscado indica:",o:["Rota de caminhões","Proibido circulação de caminhões","Peso máximo para caminhões","Estacionamento de caminhões"],c:1,cat:"sinalizacao",ex:"R-13: proibida a circulação de veículos de carga no trecho indicado."},
{p:"O que significa a marcação de 'zebra' (faixas brancas transversais) na pista?",o:["Área de obras","Faixa de travessia de pedestres","Proibido estacionar","Redução de velocidade obrigatória"],c:1,cat:"sinalizacao",ex:"As faixas de zebra (brancas e pretas ou brancas no asfalto) indicam faixa de pedestres."},
{p:"Quando dois sinais de trânsito se contradizem, deve-se obedecer:",o:["O mais antigo","O de menor tamanho","O mais restritivo","O que está mais alto"],c:2,cat:"sinalizacao",ex:"Prevalece sempre a sinalização mais restritiva para garantir a segurança."},
{p:"A placa com fundo azul e letra 'H' branca indica:",o:["Hotel","Hospital ou serviço de saúde de emergência","Heliporto","Hidráulica"],c:1,cat:"sinalizacao",ex:"'H' em azul = hospital ou posto de saúde nas proximidades."},
{p:"O que é a 'linha de retenção' na pista?",o:["Linha que separa faixas","Linha branca transversal contínua onde o veículo deve parar","Linha que delimita o acostamento","Início da faixa de pedestres"],c:1,cat:"sinalizacao",ex:"Linha de retenção: linha transversal contínua branca indicando onde o veículo deve parar (semáforos, PARE)."},
{p:"Placa com fundo vermelho e texto 'CONTRAMÃO' indica:",o:["Você está na mão correta","Você está na contramão — pare e volte","Rua de mão dupla à frente","Trevo de acesso"],c:1,cat:"sinalizacao",ex:"Placa de advertência que indica ao condutor que ele está circulando no sentido proibido."},
{p:"A placa A-21 (triângulo com bicicleta) indica:",o:["Ciclovia à frente","Proibido bicicletas","Atenção a ciclistas na pista","Estacionamento de bicicletas"],c:2,cat:"sinalizacao",ex:"A-21: triângulo amarelo com figura de ciclista = advertência sobre presença de ciclistas na pista."},
{p:"Sinalização com cone laranja na pista indica:",o:["Estacionamento permitido","Área de obras ou situação temporária de perigo","Início de rodovia","Área de lazer"],c:1,cat:"sinalizacao",ex:"Cones laranjas delimitam áreas de obras, acidentes ou situações temporárias. Têm força legal."},
{p:"O que indica a placa I-3 (retângulo azul com letra 'P')?",o:["Proibido parar","Área de estacionamento permitido","Posto policial","Parada de ônibus"],c:1,cat:"sinalizacao",ex:"I-3: placa de indicação (fundo azul) com 'P' = estacionamento disponível nas proximidades."},
{p:"A placa com símbolo de gasolina no fundo azul indica:",o:["Proibido combustível","Posto de combustível próximo","Veículos a diesel apenas","Abastecimento gratuito"],c:1,cat:"sinalizacao",ex:"I-2: retângulo azul com símbolo de posto = posto de combustível nas proximidades."},
{p:"Uma placa com triângulo amarelo e ondas (linhas onduladas) indica:",o:["Rio próximo","Pista escorregadia","Vento lateral forte","Névoa frequente"],c:1,cat:"sinalizacao",ex:"A-13 (Pista Escorregadia): triângulo com figura de carro derrapando ou ondas = pista molhada ou escorregadia."},
{p:"Qual a finalidade das marcas de canalização na pista?",o:["Indicar faixas de pedestres","Orientar o tráfego em cruzamentos e bifurcações","Marcar vagas especiais","Indicar velocidade máxima"],c:1,cat:"sinalizacao",ex:"Marcas de canalização (setas, ilhas pintadas) orientam os condutores em bifurcações e cruzamentos complexos."},

// ════════════════════════════════════════════════
//  LEGISLAÇÃO (60 questões)
// ════════════════════════════════════════════════
{p:"Qual é o prazo mínimo de suspensão da CNH por alcoolemia comprovada?",o:["6 meses","12 meses","24 meses","1 mês"],c:1,cat:"legislacao",ex:"CTB Art. 165: suspensão do direito de dirigir por 12 meses na primeira infração por álcool."},
{p:"A CNH de condutor entre 50 e 70 anos tem validade de:",o:["10 anos","5 anos","3 anos","2 anos"],c:1,cat:"legislacao",ex:"CTB Art. 159: validade de 5 anos para condutores entre 50 e 70 anos de idade."},
{p:"Para conduzir veículo de carga acima de 3.500 kg é necessária a CNH:",o:["B","C","D","E"],c:1,cat:"legislacao",ex:"CNH categoria C autoriza conduzir veículos de carga com PBT acima de 3.500 kg."},
{p:"Para conduzir ônibus com mais de 8 passageiros, a CNH necessária é:",o:["B","C","D","E"],c:2,cat:"legislacao",ex:"CNH categoria D autoriza conduzir veículos de passageiros com mais de 8 lugares."},
{p:"Quantos pontos acumula uma infração leve na CNH?",o:["2","3","4","5"],c:1,cat:"legislacao",ex:"CTB Art. 259: infração leve = 3 pontos. Ex: buzina desnecessária, equipamento com defeito leve."},
{p:"Quantos pontos acumula uma infração média na CNH?",o:["3","4","5","7"],c:1,cat:"legislacao",ex:"CTB Art. 259: infração média = 4 pontos. Ex: parar sobre faixa de pedestre."},
{p:"O CRLV (Certificado de Registro e Licenciamento de Veículo) deve ser renovado:",o:["A cada 5 anos","A cada 2 anos","Anualmente","Apenas na mudança de dono"],c:2,cat:"legislacao",ex:"O licenciamento do veículo deve ser realizado anualmente. O CRLV comprova o pagamento."},
{p:"Qual documento comprova que o veículo está licenciado para circular?",o:["CRV","CNH","CRLV","DPVAT"],c:2,cat:"legislacao",ex:"CRLV (Certificado de Registro e Licenciamento de Veículo) comprova o licenciamento anual."},
{p:"O que é o CRV?",o:["Comprovante de Revisão Veicular","Certificado de Registro de Veículo (documento de propriedade)","Carteira de Registro de Veículo","Controle de Revisão de Velocidade"],c:1,cat:"legislacao",ex:"CRV é o documento de propriedade do veículo, equivalente à escritura. Deve ficar com o proprietário."},
{p:"A vistoria obrigatória do veículo é chamada de:",o:["Revisão","Inspeção veicular","Licenciamento","Emplacamento"],c:1,cat:"legislacao",ex:"Inspeção veicular obrigatória verifica condições de segurança e emissão de poluentes."},
{p:"Qual a velocidade máxima permitida para motocicletas em rodovias de pista dupla?",o:["90 km/h","100 km/h","110 km/h","120 km/h"],c:2,cat:"legislacao",ex:"Motocicletas têm o mesmo limite que automóveis: 110 km/h em pista dupla."},
{p:"O prazo para o candidato obter a CNH após a PPD (Permissão para Dirigir) é:",o:["6 meses","1 ano","2 anos","5 anos"],c:1,cat:"legislacao",ex:"O candidato tem 1 ano de PPD. Ao final, sem infrações graves, converte para CNH definitiva."},
{p:"Em qual situação a CNH pode ser cassada?",o:["Ao acumular 15 pontos","Ao cometer homicídio culposo no trânsito","Ao recusar bafômetro pela primeira vez","Ao estacionar em vaga irregular"],c:1,cat:"legislacao",ex:"CTB Art. 263: cassação da CNH em crimes de trânsito como homicídio culposo."},
{p:"O exame médico para renovação da CNH verifica:",o:["Apenas a visão","Acuidade visual, audição e saúde geral","Somente reflexos","Apenas pressão arterial"],c:1,cat:"legislacao",ex:"O exame médico verifica condições físicas e mentais do condutor, incluindo visão e audição."},
{p:"Qual a idade mínima para conduzir ciclomotor (50cc)?",o:["16 anos","17 anos","18 anos","14 anos"],c:0,cat:"legislacao",ex:"CTB Art. 140: ciclomotores podem ser conduzidos por maiores de 16 anos, com habilitação específica."},
{p:"A penalidade para quem dirigir com CNH cassada é:",o:["Multa e suspensão","Detenção de 6 meses a 1 ano e multa","Apenas advertência","Multa gravíssima e retenção do veículo"],c:1,cat:"legislacao",ex:"CTB Art. 307: dirigir com CNH cassada = detenção de 6 meses a 1 ano e multa."},
{p:"O que é o 'direito de arrependimento' em multas de trânsito?",o:["Cancelar a multa pagando antes","Recorrer administrativamente em 30 dias","Pagar com 30% de desconto em 15 dias","Não existe esse direito no CTB"],c:1,cat:"legislacao",ex:"O condutor tem 30 dias após a notificação para apresentar recurso em primeira instância (JARI)."},
{p:"O licenciamento de veículo em atraso gera:",o:["Apenas multa","Multa e pontos na CNH","Multa e retenção do veículo","Apenas advertência"],c:2,cat:"legislacao",ex:"Veículo com licenciamento vencido é retido pelo agente de trânsito. O proprietário paga a multa e licencia."},
{p:"Quantas questões corretas são necessárias para aprovação na prova teórica do DETRAN?",o:["18","20","21","25"],c:2,cat:"legislacao",ex:"São 30 questões; são necessárias pelo menos 21 corretas (70%) para aprovação."},
{p:"O que é o RENAVAM?",o:["Registro Nacional de Veículos Automotores","Renovação Automática de Veículos","Relatório Nacional de Veículos Ativos","Regulamento de Veículos Automáticos"],c:0,cat:"legislacao",ex:"RENAVAM: número único de identificação do veículo no cadastro nacional, constante no CRV e CRLV."},
{p:"Qual o prazo para transferência de propriedade do veículo após a venda?",o:["15 dias","30 dias","45 dias","60 dias"],c:1,cat:"legislacao",ex:"CTB Art. 134: o comprador tem 30 dias para transferir o veículo ao seu nome."},
{p:"Em caso de acidente sem vítimas, os condutores devem:",o:["Esperar a polícia mesmo que não haja vítimas","Retirar os veículos da via se possível e resolver amigavelmente ou chamar seguradora","Abandonar os veículos e ir embora","Aguardar 2 horas antes de mover os veículos"],c:1,cat:"legislacao",ex:"Sem vítimas: retire os veículos se puder; preencha o BO amigável ou chame a seguradora."},
{p:"Qual infração é cometida ao transitar com veículo sem emplacamento?",o:["Leve","Média","Grave","Gravíssima"],c:3,cat:"legislacao",ex:"CTB Art. 230, I: veículo sem placa ou com placa adulterada = gravíssima (7 pontos + apreensão)."},
{p:"A CNH categoria 'ACC' permite conduzir:",o:["Automóveis e caminhões","Ciclomotores","Apenas motos de até 125 cc","Qualquer veículo leve"],c:1,cat:"legislacao",ex:"ACC (Autorização para Conduzir Ciclomotor) permite conduzir ciclomotores com motor até 50 cc."},
{p:"Qual das situações abaixo suspende imediatamente o direito de dirigir?",o:["3 infrações leves em 1 ano","Alcoolemia comprovada acima de 0,33 mg/L","1 infração grave","Multa não paga há 6 meses"],c:1,cat:"legislacao",ex:"CTB Art. 165-A: alcoolemia acima de 0,33 mg/L gera crime de trânsito e suspensão imediata da CNH."},
{p:"Ao reformar um veículo alterando suas características, o proprietário deve:",o:["Apenas comunicar ao DETRAN por carta","Fazer nova vistoria e atualizar o CRV no DETRAN","Apenas atualizar o seguro","Não é necessária nenhuma ação"],c:1,cat:"legislacao",ex:"Alterações nas características do veículo exigem nova vistoria e atualização no registro do DETRAN."},
{p:"O CTB (Código de Trânsito Brasileiro) entrou em vigor em:",o:["1966","1988","1998","2002"],c:2,cat:"legislacao",ex:"O CTB (Lei 9.503) foi promulgado em 23/09/1997 e entrou em vigor em 22/01/1998."},
{p:"Qual é o órgão máximo de trânsito no Brasil?",o:["DETRAN","PRF","CONTRAN","DENATRAN"],c:2,cat:"legislacao",ex:"CONTRAN (Conselho Nacional de Trânsito) é o órgão máximo normativo e coordenador do Sistema Nacional de Trânsito."},
{p:"Para conduzir veículo com reboque acima de 6.000 kg, a CNH necessária é:",o:["C","D","E","B"],c:2,cat:"legislacao",ex:"CNH categoria E autoriza conduzir combinações de veículos com reboque ou semirreboque acima de 6.000 kg."},
{p:"O prazo para pagamento de multa com desconto de 40% é:",o:["15 dias","30 dias","20 dias","45 dias"],c:1,cat:"legislacao",ex:"O condutor tem 30 dias após a notificação para pagar com 40% de desconto (sem recorrer)."},
{p:"Quantos pontos acumula uma infração gravíssima com fator multiplicador 3?",o:["7","14","21","10"],c:2,cat:"legislacao",ex:"Fator multiplicador 3 x 7 pontos = 21 pontos por infração. Ex: exceder velocidade acima de 50%."},
{p:"O limite de álcool para responsabilidade criminal (crime) é:",o:["Qualquer quantidade detectável","Acima de 0,05 mg/L","Acima de 0,33 mg/L","Acima de 0,50 mg/L"],c:2,cat:"legislacao",ex:"CTB Art. 306: crime de trânsito por embriaguez a partir de 0,33 mg/L no ar alveolar."},
{p:"O que é a JARI?",o:["Junta de Administração e Recursos de Infrações","Junta Administrativa de Recursos de Infrações","Julgamento Administrativo de Recursos de Infrações","Junta de Avaliação e Revisão de Infrações"],c:1,cat:"legislacao",ex:"JARI: Junta Administrativa de Recursos de Infrações — onde o condutor apresenta recurso em 1ª instância."},
{p:"Menor de 18 anos pode se habilitar para conduzir:",o:["Nenhum tipo de veículo","Apenas bicicletas","Ciclomotores a partir dos 16 anos","Apenas veículos elétricos"],c:2,cat:"legislacao",ex:"A partir dos 16 anos é possível obter a ACC para ciclomotores. CNH regular exige 18 anos."},
{p:"Qual a penalidade para condutor flagrado usando celular ao volante?",o:["Leve — 3 pontos","Grave — 5 pontos","Gravíssima — 7 pontos + multa R$ 293,47","Média — 4 pontos"],c:2,cat:"legislacao",ex:"CTB Art. 252, IX: celular ao volante = gravíssima, 7 pontos, multa R$ 293,47."},
{p:"A transferência de pontuação de multa para outro condutor é:",o:["Permitida se houver concordância","Permitida apenas para familiares","Proibida — a pontuação é pessoal e intransferível","Permitida mediante declaração notariada"],c:2,cat:"legislacao",ex:"A pontuação da CNH é pessoal e intransferível. Somente o condutor identificado como infrator responde."},
{p:"O recurso de segunda instância de multa de trânsito é julgado pelo:",o:["DETRAN","CONTRAN ou CETRAN","Juizado Especial de Trânsito","PRF"],c:1,cat:"legislacao",ex:"Após a JARI (1ª instância), o recurso vai ao CETRAN (estadual) ou CONTRAN (federal)."},
{p:"Qual o limite de velocidade para motos em vias locais urbanas?",o:["20 km/h","30 km/h","40 km/h","50 km/h"],c:1,cat:"legislacao",ex:"CTB Art. 61: vias locais urbanas — 30 km/h para todos os veículos, incluindo motos."},
{p:"O que acontece com pontos na CNH após 12 meses sem nova infração?",o:["São zerados automaticamente","Permanecem por mais 12 meses","São transferidos para o veículo","Ficam registrados por 5 anos"],c:0,cat:"legislacao",ex:"CTB Art. 261: após 12 meses sem nova infração, os pontos são zerados no prontuário do condutor."},

// ════════════════════════════════════════════════
//  DIREÇÃO DEFENSIVA (60 questões)
// ════════════════════════════════════════════════
{p:"O que é direção defensiva?",o:["Dirigir no limite máximo de velocidade","Dirigir com antecedência, atenção e conhecimento para evitar acidentes","Usar todos os equipamentos de segurança","Respeitar apenas os semáforos"],c:1,cat:"direcao",ex:"Direção defensiva: conjunto de atitudes e técnicas para prever e evitar acidentes independente dos erros alheios."},
{p:"A distância de segurança entre veículos deve ser:",o:["Sempre 2 metros","Suficiente para frear com segurança se o veículo à frente parar bruscamente","Metade do comprimento do veículo","Apenas necessária em rodovias"],c:1,cat:"direcao",ex:"A distância depende da velocidade, condições da pista e do veículo. Deve garantir frenagem segura."},
{p:"Ao sair de uma garagem em via pública, o condutor deve:",o:["Sair rapidamente para não atrapalhar o trânsito","Buzinar e sair","Verificar se há pedestres e veículos, e ceder passagem a todos","Acender o farol alto"],c:2,cat:"direcao",ex:"Ao sair de garagem, o pedestre na calçada e o veículo na via têm preferência absoluta."},
{p:"Em caso de falha nos freios em descida longa, o que fazer?",o:["Desligar o motor imediatamente","Usar marcha baixa para frear com motor, tentar o freio de mão suavemente","Acelerar para controlar","Virar bruscamente para o lado"],c:1,cat:"direcao",ex:"Freio motor + freio de estacionamento gradual. Nunca trave bruscamente pois perde o controle direcional."},
{p:"Ao se aproximar de um cruzamento à noite, deve-se:",o:["Manter o farol alto para ver melhor","Alternar entre alto e baixo para sinalizar","Reduzir a velocidade e usar farol baixo","Apagar os faróis para não ofuscar"],c:2,cat:"direcao",ex:"Farol baixo em cruzamentos evita ofuscar outros condutores. Reduza a velocidade e observe os lados."},
{p:"Em rodovias, qual é a conduta correta na faixa da esquerda?",o:["Usá-la livremente em qualquer situação","Utilizá-la somente para ultrapassagem, retornando depois à direita","Permanecer nela se estiver na velocidade máxima","Usá-la apenas para emergências"],c:1,cat:"direcao",ex:"A faixa da esquerda é para ultrapassagem. Após ultrapassar, volte à faixa da direita."},
{p:"Ao encontrar neblina densa, o condutor deve:",o:["Parar no meio da pista","Usar farol alto para ver mais longe","Usar farol de neblina, reduzir velocidade e aumentar distância","Acelerar para sair da neblina rapidamente"],c:2,cat:"direcao",ex:"Farol de neblina (ou baixo) + velocidade reduzida + maior distância de segurança."},
{p:"Quais são os pontos cegos de um veículo?",o:["Regiões visíveis pelos espelhos retrovisores","Regiões não visíveis pelos espelhos retrovisores","Apenas a parte traseira do veículo","Apenas a frente do veículo"],c:1,cat:"direcao",ex:"Pontos cegos: áreas ao redor do veículo não cobertas pelos espelhos. Caminhões têm pontos cegos muito amplos."},
{p:"Como deve ser feita a frenagem em curvas?",o:["Frear dentro da curva para maior segurança","Frear antes da curva, não dentro dela","Frear apenas com o freio de mão","Não é necessário frear em curvas"],c:1,cat:"direcao",ex:"Frenagem em curva pode causar derrapagem. Reduza ANTES da curva e mantenha velocidade constante."},
{p:"Ao estacionar em aclive (subida) SEM guia, as rodas dianteiras ficam:",o:["Viradas para a esquerda (para fora da pista)","Viradas para a direita (para dentro da pista)","Retas","Tanto faz"],c:0,cat:"direcao",ex:"Sem guia: vire as rodas para fora (esquerda na subida). Se rolar, o veículo sai da pista, não vai para a via."},
{p:"Qual a conduta correta ao perceber que vai colidir inevitavelmente?",o:["Fechar os olhos","Tentar desviar ou reduzir o impacto dirigindo para área menos perigosa","Acelerar e buzinar","Saltar do veículo"],c:1,cat:"direcao",ex:"Tente reduzir a velocidade ao máximo. Desvie para local menos perigoso (gramado, acostamento)."},
{p:"A 'zona de proteção' ao ultrapassar um ciclista exige:",o:["50 cm de distância lateral","1 metro de distância lateral","1,5 metro de distância lateral","2 metros de distância lateral"],c:2,cat:"direcao",ex:"CTB: ao ultrapassar ciclista, mantenha distância lateral mínima de 1,5 metro por segurança."},
{p:"Em situação de aquaplanagem, o correto é:",o:["Frear bruscamente","Acelerar para sair da lâmina de água","Soltar o acelerador gradualmente e não frear bruscamente","Virar o volante para o lado"],c:2,cat:"direcao",ex:"Na aquaplanagem, solte o acelerador suavemente. Frenagem brusca piora a situação."},
{p:"Qual a conduta ao perceber fadiga ou sonolência ao volante?",o:["Tomar café e continuar","Abrir a janela e continuar","Parar em local seguro e descansar","Acelerar para chegar logo"],c:2,cat:"direcao",ex:"Sonolência é responsável por muitos acidentes graves. A única solução é PARAR e descansar."},
{p:"Como se faz o uso correto dos espelhos retrovisores?",o:["Apenas antes de frear","A cada 5 a 8 segundos e sempre antes de qualquer manobra","Apenas ao fazer curvas","Somente em rodovias"],c:1,cat:"direcao",ex:"Verificar os espelhos a cada 5-8 segundos e SEMPRE antes de mudar de faixa, curvar ou frear."},
{p:"O que é 'freio motor'?",o:["Um tipo de freio auxiliar instalado em ônibus","Usar a resistência do motor reduzindo a marcha para desacelerar","O freio de mão","Frear usando apenas o pedal de freio"],c:1,cat:"direcao",ex:"Freio motor: engrenar marchas inferiores para que o motor desacelere o veículo sem usar o freio."},
{p:"Ao trafegar atrás de um caminhão, qual a principal preocupação?",o:["Que o caminhão bata no seu carro","Ponto cego do caminhão e poeira na pista","Que o caminhão freie bruscamente sem ver você","Que a esteira de vento atrapalhe"],c:2,cat:"direcao",ex:"Se você não vê os espelhos do caminhão, o motorista não vê você. Mantenha distância segura."},
{p:"Ao fazer retorno em rodovia, o condutor deve:",o:["Fazê-lo no acostamento","Fazê-lo apenas nos locais sinalizados para retorno","Fazê-lo em qualquer ponto onde não haja veículos","Fazê-lo apenas à noite"],c:1,cat:"direcao",ex:"O retorno em rodovias só é permitido nos locais sinalizados. Jamais faça retorno em locais proibidos."},
{p:"Em pista molhada, a distância de frenagem:",o:["Diminui","Permanece igual","Aumenta significativamente","Depende apenas do veículo"],c:2,cat:"direcao",ex:"Em pista molhada, a frenagem pode ser até 3x maior. Aumente a distância de segurança."},
{p:"O condutor deve ligar o farol baixo em qual situação abaixo?",o:["Apenas à noite","Apenas em chuva forte","Em rodovias durante o dia e à noite, e em qualquer condição de baixa visibilidade","Somente em túneis"],c:2,cat:"direcao",ex:"CTB Art. 40: farol baixo obrigatório em rodovias 24h e em qualquer condição de baixa visibilidade."},
{p:"Qual a conduta correta ao receber luz alta de um veículo em sentido contrário?",o:["Ligar o farol alto em resposta","Piscar o farol alto repetidamente","Desviar os olhos para a direita e reduzir a velocidade","Parar o veículo"],c:2,cat:"direcao",ex:"Não olhe diretamente para a luz. Desvie o olhar para a borda direita da pista e reduza a velocidade."},
{p:"Para realizar uma ultrapassagem segura, você precisa ter:",o:["Apenas velocidade superior ao veículo à frente","Visibilidade suficiente, espaço, velocidade e certeza de que pode completar a manobra","Apenas espaço à frente","Apenas boa iluminação"],c:1,cat:"direcao",ex:"Ultrapassagem segura exige: visibilidade total, espaço suficiente, velocidade para completar e pista livre."},
{p:"Ao deixar um veículo estacionado em via pública à noite, deve-se:",o:["Desligar todas as luzes para economizar bateria","Ligar as luzes de posição (lanterna)","Ligar o pisca-alerta","Não é necessário nenhum procedimento especial"],c:1,cat:"direcao",ex:"Veículo parado à noite deve ter luzes de posição ligadas para ser visto pelos outros condutores."},
{p:"Ao trafegar em pista com buracos, o condutor deve:",o:["Acelerar para atravessá-los rápido","Zigzaguear entre os buracos sem sinalizar","Reduzir a velocidade e sinalizar aos que vêm atrás","Usar apenas a faixa da esquerda"],c:2,cat:"direcao",ex:"Reduza, pise suavemente nos buracos e pisque os freios para avisar o veículo de trás."},
{p:"Em um túnel, ao ocorrer pane no veículo, deve-se:",o:["Permanecer no veículo com as portas fechadas","Sair do veículo, colocar o triângulo e buscar saída de emergência","Ligar o motor e aguardar socorro","Tentar empurrar o veículo sozinho"],c:1,cat:"direcao",ex:"Em túneis: sinalize, saia com segurança e busque a saída de emergência. Não permaneça no veículo."},

// ════════════════════════════════════════════════
//  INFRAÇÕES (60 questões)
// ════════════════════════════════════════════════
{p:"Ultrapassar pelo acostamento é infração:",o:["Leve","Média","Grave","Gravíssima"],c:3,cat:"infrações",ex:"CTB Art. 193: ultrapassar pelo acostamento = gravíssima, 7 pontos."},
{p:"Trafegar na contramão é infração:",o:["Leve","Média","Grave","Gravíssima"],c:3,cat:"infrações",ex:"CTB Art. 186, III: trafegar na contramão = gravíssima, 7 pontos."},
{p:"Não usar o cinto de segurança é infração:",o:["Leve","Média","Grave","Gravíssima"],c:2,cat:"infrações",ex:"CTB Art. 167: sem cinto = grave, 5 pontos. Vale para motorista e todos os passageiros."},
{p:"Exceder em até 20% a velocidade máxima é infração:",o:["Leve","Média","Grave","Gravíssima"],c:2,cat:"infrações",ex:"CTB Art. 218, I: exceder velocidade em até 20% = grave (5 pontos)."},
{p:"Exceder entre 20% e 50% a velocidade máxima é infração:",o:["Média","Grave","Gravíssima fator 2","Gravíssima fator 3"],c:2,cat:"infrações",ex:"CTB Art. 218, II: entre 20% e 50% acima do limite = gravíssima com multiplicador 2 (14 pontos)."},
{p:"Avançar sinal vermelho gera quantos pontos na CNH?",o:["3","4","5","7"],c:3,cat:"infrações",ex:"CTB Art. 208: avançar vermelho = gravíssima, 7 pontos, multa R$ 293,47."},
{p:"Dirigir falando ao celular segurado na mão gera quantos pontos?",o:["3","4","5","7"],c:3,cat:"infrações",ex:"CTB Art. 252, IX: uso de celular ao volante = gravíssima, 7 pontos."},
{p:"Não respeitar a faixa de pedestre é infração:",o:["Leve","Média","Grave","Gravíssima"],c:2,cat:"infrações",ex:"CTB Art. 214: não ceder passagem ao pedestre na faixa = grave, 5 pontos."},
{p:"Qual a penalidade por estacionar em frente a hidrante?",o:["Leve","Média","Grave","Gravíssima"],c:3,cat:"infrações",ex:"CTB Art. 181, VI: estacionar em frente a hidrante = gravíssima, 7 pontos + remoção."},
{p:"Deixar o veículo com motor ligado em local fechado é infração:",o:["Leve","Média","Grave","Não é infração"],c:0,cat:"infrações",ex:"CTB Art. 228, I: manter motor desnecessariamente = leve, 3 pontos."},
{p:"Não sinalizar retorno ou mudança de direção é infração:",o:["Leve","Média","Grave","Gravíssima"],c:1,cat:"infrações",ex:"CTB Art. 244 (para motos) e Art. 241: deixar de sinalizar mudança de direção = média, 4 pontos."},
{p:"Dirigir veículo com pneus sem sulco (carecas) é infração:",o:["Leve","Média","Grave","Gravíssima"],c:1,cat:"infrações",ex:"CTB Art. 230, II: conduzir veículo com pneus fora de especificação = média, 4 pontos."},
{p:"Qual a punição para quem faz racha ou apostas em via pública?",o:["Gravíssima + multa","Gravíssima + crime + suspensão + possível prisão","Grave + multa","Apenas apreensão do veículo"],c:1,cat:"infrações",ex:"CTB Art. 308: racha = crime, pena de 6 meses a 3 anos + multa + suspensão + apreensão do veículo."},
{p:"Estacionar em calçada é infração:",o:["Leve","Média","Grave","Gravíssima"],c:3,cat:"infrações",ex:"CTB Art. 181, VIII: estacionar sobre calçada = gravíssima, 7 pontos + remoção."},
{p:"Não dar passagem a veículos de emergência (ambulância, bombeiros) é infração:",o:["Leve","Média","Grave","Gravíssima"],c:2,cat:"infrações",ex:"CTB Art. 196: não dar passagem a veículo de emergência com sinal sonoro ligado = grave, 5 pontos."},
{p:"Exceder em mais de 50% a velocidade máxima é infração:",o:["Grave","Gravíssima fator 2","Gravíssima fator 3","Apenas crime"],c:2,cat:"infrações",ex:"CTB Art. 218, III: acima de 50% do limite = gravíssima com multiplicador 3 (21 pontos)."},
{p:"Usar o veículo para empurrar ou rebocar outro irregularmente é infração:",o:["Leve","Média","Grave","Não é infração"],c:1,cat:"infrações",ex:"CTB Art. 230, XIV: reboque irregular sem equipamento adequado = média, 4 pontos."},
{p:"Parar o veículo sobre trilhos de trem é infração:",o:["Leve","Média","Grave","Gravíssima"],c:3,cat:"infrações",ex:"CTB Art. 181, XI: parar sobre trilhos = gravíssima, 7 pontos + risco à segurança."},
{p:"Dirigir com visibilidade obstruída (excesso de itens no para-brisa) é infração:",o:["Leve","Média","Grave","Não é infração"],c:1,cat:"infrações",ex:"CTB Art. 230, III: para-brisa, vidros e espelhos obstruídos = média, 4 pontos."},
{p:"Qual a penalidade para quem dirige sem estar habilitado (sem CNH)?",o:["Grave — 5 pontos","Gravíssima — 7 pontos + retenção do veículo","Apenas multa","Leve — 3 pontos"],c:1,cat:"infrações",ex:"CTB Art. 162: dirigir sem CNH = gravíssima, 7 pontos, multa + retenção do veículo."},
{p:"Falar ao celular viva-voz sem segurar é:",o:["Proibido — mesma infração","Permitido — não é infração","Permitido com fone de ouvido","Depende da velocidade"],c:1,cat:"infrações",ex:"CTB Art. 252: o uso de celular proibido é o que implique segurar o aparelho. Viva-voz é permitido."},
{p:"Transportar passageiro na parte externa do veículo é infração:",o:["Leve","Média","Grave","Gravíssima"],c:3,cat:"infrações",ex:"CTB Art. 230, IX: transportar passageiro fora do habitáculo = gravíssima, 7 pontos."},
{p:"Cometer infração de trânsito sob efeito de álcool tem penalidade:",o:["Normal — mesma que sem álcool","Agravada em dobro","Agravada com suspensão imediata da CNH","Apenas advertência"],c:2,cat:"infrações",ex:"CTB Art. 276: qualquer infração cometida sob efeito de álcool tem pena agravada + suspensão imediata."},
{p:"Estacionar na faixa de pedestres é infração:",o:["Leve","Média","Grave","Gravíssima"],c:3,cat:"infrações",ex:"CTB Art. 181, IX: parar na faixa de pedestres = média (4 pts). Estacionar = gravíssima (7 pts)."},
{p:"Não usar capacete na moto é infração para:",o:["Apenas o piloto","Apenas o garupa","Piloto e passageiro — ambos são infrações separadas","O responsável pelo veículo"],c:2,cat:"infrações",ex:"CTB Art. 244, V: tanto piloto quanto passageiro sem capacete geram infrações separadas (grave cada)."},
{p:"Usar o acostamento como faixa de rolamento em congestionamento é:",o:["Permitido em congestionamento","Grave infração — proibido","Permitido por até 500 metros","Apenas para motos"],c:1,cat:"infrações",ex:"CTB Art. 193: usar o acostamento como via de tráfego regular = gravíssima, 7 pontos."},
{p:"Deixar de prestar socorro a vítima de acidente que você causou é:",o:["Infração administrativa","Crime com reclusão de 1 a 3 anos","Infração grave","Apenas multa"],c:1,cat:"infrações",ex:"CTB Art. 302: homicídio culposo no trânsito com fuga = crime com pena de 2 a 4 anos + cassação da CNH."},
{p:"Qual a penalidade por transitar com veículo com escapamento adulterado?",o:["Leve","Média","Grave","Gravíssima"],c:1,cat:"infrações",ex:"CTB Art. 230: escapamento adulterado causando barulho excessivo = média, 4 pontos."},
{p:"Parar o veículo em cima da calçada para estacionar na garagem é:",o:["Permitido por até 5 minutos","Proibido — infração grave","Permitido se não atrapalhar pedestres","Apenas proibido à noite"],c:1,cat:"infrações",ex:"CTB Art. 181: parar sobre calçada = infração. A calçada é exclusiva para pedestres."},
{p:"Trafegar em rodovia sem usar o farol aceso durante o dia é infração:",o:["Não é infração","Leve — 3 pontos","Média — 4 pontos","Grave — 5 pontos"],c:2,cat:"infrações",ex:"CTB Art. 40: farol baixo obrigatório em rodovias durante o dia. Deixar de usar = média, 4 pontos."},

// ════════════════════════════════════════════════
//  SEGURANÇA E PRIMEIROS SOCORROS (60 questões)
// ════════════════════════════════════════════════
{p:"Ao encontrar vítima inconsciente em acidente, o primeiro passo é:",o:["Mover a vítima para longe do veículo","Verificar responsividade e chamar socorro (192/193)","Dar água","Colocar o cinto"],c:1,cat:"seguranca",ex:"Protocolo de primeiros socorros: verifique responsividade, chame socorro. Só mova se houver risco de vida."},
{p:"Como verificar se uma vítima está respirando?",o:["Ver, ouvir e sentir ar saindo do nariz e boca","Verificar se está falando","Checar o pulso no pescoço","Observar a cor da pele"],c:0,cat:"seguranca",ex:"VOS: Ver (se o peito sobe), Ouvir (sons de respiração) e Sentir (ar na face) — por até 10 segundos."},
{p:"Quando se inicia o RCP (ressuscitação cardiopulmonar)?",o:["Quando a vítima está inconsciente e respirando","Quando a vítima está inconsciente e NÃO respira normalmente","Quando a vítima está consciente mas em dor","Quando a vítima está com hemorragia"],c:1,cat:"seguranca",ex:"RCP é indicada quando a vítima está inconsciente E sem respiração normal (ausente ou agônica)."},
{p:"A taxa de compressões no RCP em adultos deve ser:",o:["50-60 por minuto","80-100 por minuto","100-120 por minuto","140-160 por minuto"],c:2,cat:"seguranca",ex:"O RCP eficaz usa 100-120 compressões por minuto, profundidade de 5-6 cm no centro do peito."},
{p:"Em caso de hemorragia grave no braço, o correto é:",o:["Aplicar gelo e esperar","Comprimir o ferimento com pano limpo e pressão firme","Soltar o curativo de tempos em tempos","Aplicar torniquete imediatamente em qualquer hemorragia"],c:1,cat:"seguranca",ex:"Compressão direta com pano limpo é o primeiro passo. Torniquete apenas se a hemorragia não ceder."},
{p:"Qual o número de emergência do SAMU?",o:["190","191","192","193"],c:2,cat:"seguranca",ex:"SAMU: 192. Bombeiros: 193. PM: 190. PRF: 191."},
{p:"Qual o número dos Bombeiros?",o:["190","191","192","193"],c:3,cat:"seguranca",ex:"Bombeiros: 193. SAMU: 192. PM: 190. PRF: 191."},
{p:"Em caso de suspeita de lesão na coluna vertebral, deve-se:",o:["Levantar a vítima imediatamente","Não mover a vítima, salvo risco imediato de vida","Girar a cabeça da vítima para o lado","Sentar a vítima"],c:1,cat:"seguranca",ex:"Suspeita de coluna: NÃO mova a vítima. O movimento errado pode causar paralisia permanente."},
{p:"Se uma vítima está engasgada e consciente, a manobra indicada é:",o:["Fazer boca a boca","Manobra de Heimlich (compressão abdominal)","Colocar a vítima deitada","Dar tapas nas costas apenas se a manobra de Heimlich falhar"],c:1,cat:"seguranca",ex:"Manobra de Heimlich: compressões abdominais para expelir o objeto obstruindo a via aérea."},
{p:"O que fazer se um pneu traseiro furar em alta velocidade?",o:["Frear bruscamente","Acelerar e depois frear","Segurar o volante firme, não frear bruscamente e reduzir gradualmente","Virar o volante para o lado do furo"],c:2,cat:"seguranca",ex:"Furo de pneu traseiro: mantenha o volante firme, solte o acelerador gradualmente. Não freie bruscamente."},
{p:"O que é o 'efeito cascata' em acidentes?",o:["Um veículo bater em outro que bate em outro, em série","A derrapagem em cascalho","Aquaplanagem em curva","Colisão em série na neblina"],c:0,cat:"seguranca",ex:"Efeito cascata: batidas em série. Resultado de curta distância de segurança entre veículos."},
{p:"Como agir ao ver fumaça saindo do capô em movimento?",o:["Continuar até o posto","Parar com segurança, desligar o motor, sair e afastar-se","Jogar água imediatamente","Abrir o capô enquanto dirige"],c:1,cat:"seguranca",ex:"Fumaça no capô = risco de incêndio. Pare, desligue o motor, saia e afaste-se. Ligue para bombeiros."},
{p:"A faixa de alcoolemia que configura crime de trânsito é:",o:["Qualquer quantidade","Acima de 0,05 mg/L no sangue","Acima de 0,33 mg/L no ar alveolar","Acima de 1,0 mg/L no sangue"],c:2,cat:"seguranca",ex:"CTB Art. 306: crime a partir de 0,33 mg/L no ar alveolar (equivale a ~0,6 g/L no sangue)."},
{p:"Ao socorrer vítima de acidente com choque elétrico, deve-se:",o:["Puxar a vítima pelo braço","Desligar a energia antes de tocá-la","Molhar a vítima para conduzir melhor a eletricidade","Dar respiração boca a boca imediatamente"],c:1,cat:"seguranca",ex:"Nunca toque na vítima de choque elétrico sem desligar a energia. O socorrista pode ser eletrocutado."},
{p:"A quantidade mínima de água que deve ser ingerida em viagens longas é:",o:["0,5 L por hora","1,5 a 2 L por dia","250 mL por dia","Não há recomendação"],c:1,cat:"seguranca",ex:"Desidratação leve afeta o tempo de reação. Beba pelo menos 1,5 a 2 litros de água por dia em viagens."},
{p:"O que causa a 'fadiga de rodovia'?",o:["Excesso de velocidade","Monotonia da paisagem e baixa estimulação, causando sono","Consumo de alimentos pesados","Calor excessivo"],c:1,cat:"seguranca",ex:"Fadiga de rodovia: trajeção monótona em retas longas induz sonolência involuntária."},
{p:"Medicamentos que causam sonolência (antihistamínicos, calmantes) e direção:",o:["São permitidos com cautela","São proibidos ao dirigir","Só são perigosos em doses altas","Podem ser usados se a viagem for curta"],c:1,cat:"seguranca",ex:"Qualquer medicamento que cause sonolência compromete a direção. Consulte o médico e evite dirigir."},
{p:"O sistema de freios ABS serve para:",o:["Frear mais rápido que o sistema convencional","Evitar o travamento das rodas durante a frenagem","Controlar a tração em piso irregular","Aumentar a potência do freio de mão"],c:1,cat:"seguranca",ex:"ABS (Anti-lock Braking System): evita o travamento das rodas, permitindo controle direcional durante a frenagem."},
{p:"O que é o controle de estabilidade eletrônico (ESP)?",o:["Sistema que controla a velocidade máxima","Sistema que detecta e corrige derrapagens","Sistema de freio de emergência automático","Controle automático de faróis"],c:1,cat:"seguranca",ex:"ESP: detecta quando o veículo começa a derrapar e aplica freio seletivamente para corrigi-lo."},
{p:"Criança com até qual peso deve usar assento de bebê (bebê conforto)?",o:["Até 9 kg","Até 13 kg","Até 15 kg","Até 18 kg"],c:1,cat:"seguranca",ex:"Bebê conforto (grupo 0+): de 0 a 13 kg. Sempre voltado para trás no banco traseiro."},
{p:"A partir de qual altura a criança pode usar apenas o cinto de segurança?",o:["1,30 m","1,40 m","1,45 m","1,50 m"],c:2,cat:"seguranca",ex:"Crianças acima de 1,45 m (grupo III encerrado) podem usar apenas o cinto de segurança adulto."},
{p:"O tempo máximo de condução contínua sem pausa é:",o:["2 horas","3 horas","4 horas","6 horas"],c:2,cat:"seguranca",ex:"CTB Art. 67-C: máximo 4 horas de condução contínua. Pausa mínima de 30 minutos obrigatória."},
{p:"Em caso de incêndio no veículo dentro de um túnel:",o:["Mantenha o veículo em movimento para sair do túnel","Pare o mais longe possível das paredes, saia e use a saída de emergência","Tente apagar o fogo com o extintor no veículo","Aguarde no veículo com janelas fechadas"],c:1,cat:"seguranca",ex:"Em túnel: pare longe das paredes, desligue o motor, saia, busque saída de emergência e ligue 193."},
{p:"Qual é a função do airbag lateral?",o:["Proteger apenas o motorista","Proteger ocupantes em colisões laterais","Substituir o cinto de segurança","Funcionar apenas em capotamentos"],c:1,cat:"seguranca",ex:"Airbags laterais (de cortina e de tórax) protegem os ocupantes em colisões de lado."},

// ════════════════════════════════════════════════
//  MECÂNICA BÁSICA (60 questões)
// ════════════════════════════════════════════════
{p:"O fluido de freio deve ser trocado a cada:",o:["5.000 km","10.000 km","Conforme manual — geralmente a cada 2 anos ou 40.000 km","Apenas quando o pedal ficar mole"],c:2,cat:"mecanica",ex:"Fluido de freio absorve umidade ao longo do tempo, reduzindo a temperatura de ebulição. Troque conforme o manual."},
{p:"Qual a função do filtro de ar do motor?",o:["Filtrar a gasolina","Filtrar o ar que entra no motor, removendo impurezas","Regular a temperatura do motor","Limpar o óleo do motor"],c:1,cat:"mecanica",ex:"Filtro de ar sujo reduz a eficiência do motor e aumenta o consumo. Troque conforme o manual."},
{p:"O que indica o piloto de temperatura do motor no vermelho?",o:["Motor em temperatura ideal","Motor superaquecido — pare imediatamente","Motor frio","Baixo nível de óleo"],c:1,cat:"mecanica",ex:"Motor no vermelho = superaquecimento. Pare com segurança, desligue e aguarde resfriar antes de abrir o radiador."},
{p:"Qual a função da embreagem?",o:["Frear o veículo","Desconectar o motor da caixa de câmbio para trocar marchas","Regular a potência do motor","Controlar a direção"],c:1,cat:"mecanica",ex:"A embreagem desacopla temporariamente o motor da transmissão, permitindo a troca de marchas."},
{p:"O que é o alternador?",o:["Um tipo de motor elétrico auxiliar","Componente que gera eletricidade para carregar a bateria enquanto o motor funciona","Sistema de arrefecimento alternativo","Bomba de combustível elétrica"],c:1,cat:"mecanica",ex:"Alternador: gera corrente elétrica alternada que é convertida para carregar a bateria e alimentar os sistemas."},
{p:"Qual a função do radiador?",o:["Refrigerar o óleo do motor","Dissipar o calor do líquido de arrefecimento do motor","Filtrar o ar do habitáculo","Controlar a pressão do combustível"],c:1,cat:"mecanica",ex:"Radiador: troca de calor entre o líquido de arrefecimento (quente vindo do motor) e o ar externo."},
{p:"Pneu calibrado com menos pressão do que o recomendado causa:",o:["Maior conforto e menor desgaste","Desgaste nas bordas e maior risco de estouro, além de maior consumo","Maior durabilidade","Menor consumo de combustível"],c:1,cat:"mecanica",ex:"Pneu sub-calibrado: desgasta as bordas, superaquece, aumenta o consumo e risco de estouro."},
{p:"Pneu calibrado com mais pressão do que o recomendado causa:",o:["Maior durabilidade e menor desgaste","Desgaste no centro do pneu e menor aderência","Maior conforto na direção","Menor consumo de combustível"],c:1,cat:"mecanica",ex:"Pneu super-calibrado: desgasta o centro, reduz a área de contato e a aderência da borracha."},
{p:"A função do sistema de escapamento é:",o:["Filtrar o ar de entrada","Conduzir e tratar os gases de combustão do motor para fora","Aumentar a potência do motor","Controlar a temperatura do motor"],c:1,cat:"mecanica",ex:"Escapamento: conduz os gases de combustão do motor, reduz ruído e trata emissões (com catalisador)."},
{p:"O que fazer quando a luz de bateria acende no painel em movimento?",o:["Continuar até o destino","Ligar ar condicionado e rádio para testar","Ir a um serviço mecânico o quanto antes — possível problema no alternador","Desligar e religar o veículo"],c:2,cat:"mecanica",ex:"Luz de bateria = alternador pode estar com defeito. O veículo pode parar em minutos. Vá a um mecânico."},
{p:"Qual a função da bomba d'água no motor?",o:["Bombear água para o limpador de para-brisa","Fazer circular o líquido de arrefecimento pelo motor e radiador","Pressurizar o combustível","Limpar o sistema de injeção"],c:1,cat:"mecanica",ex:"Bomba d'água: faz o líquido de arrefecimento circular pelo motor e pelo radiador, controlando a temperatura."},
{p:"Ruídos metálicos nos freios ao travar indicam:",o:["Freios bem ajustados","Pastilha desgastada ou disco danificado — revisão urgente","Pneu com pressão baixa","Rolamento da roda com folga"],c:1,cat:"mecanica",ex:"Rangido metálico nos freios = pastilhas no limite ou disco danificado. Perigoso — revise imediatamente."},
{p:"O que é a 'marcha lenta' (ralenti)?",o:["A menor marcha da caixa de câmbio","A rotação mínima do motor mantida quando o veículo está parado com o motor ligado","A velocidade máxima em primeira marcha","Condução em baixíssima velocidade"],c:1,cat:"mecanica",ex:"Marcha lenta (ralenti): o motor funciona na rotação mínima para se manter ligado sem o pé no acelerador."},
{p:"Qual o principal componente do sistema de direção hidráulica?",o:["Bomba de direção","Volante ajustável","Palhetas de ar","Servo freio"],c:0,cat:"mecanica",ex:"Bomba de direção hidráulica: pressuriza o fluido que auxilia o condutor a girar o volante com menos esforço."},
{p:"Se o veículo 'bate pneu' (oscila lateralmente) em alta velocidade, o problema mais provável é:",o:["Falta de óleo","Pneu desbalanceado ou convergência incorreta","Alternador com defeito","Freios gastos"],c:1,cat:"mecanica",ex:"Oscilação lateral (shimmy) geralmente indica pneu desbalanceado, pneu danificado ou problemas de alinhamento."},
{p:"A 'vela de ignição' tem função de:",o:["Verificar o nível de óleo","Produzir a faísca que inflama a mistura ar/combustível no motor","Regular a injeção de combustível","Controlar a temperatura do motor"],c:1,cat:"mecanica",ex:"Vela de ignição: produz a centelha elétrica que inflama a mistura ar/combustível no cilindro do motor."},
{p:"O líquido de arrefecimento deve ser trocado a cada:",o:["5.000 km","20.000 km","Conforme o manual — geralmente entre 40.000 e 60.000 km","Apenas quando o motor aquecer"],c:2,cat:"mecanica",ex:"Líquido de arrefecimento perde propriedades anticorrosivas e anticongelantes. Troque conforme o manual."},
{p:"O que indica vibração no pedal de freio ao frear?",o:["Freios funcionando normalmente com ABS ativo","Disco de freio empenado ou desgastado irregularmente","Falta de fluido de freio","Problema na embreagem"],c:1,cat:"mecanica",ex:"Vibração no pedal ao frear = disco de freio empenado. Necessita troca ou retífica do disco."},
{p:"Em veículo flex-fuel, o sensor lambda (sonda lambda) serve para:",o:["Medir o nível de combustível","Detectar a proporção ar/combustível e ajustar a injeção","Controlar o ABS","Medir a temperatura do motor"],c:1,cat:"mecanica",ex:"Sonda lambda: mede o oxigênio nos gases de escape para a ECU ajustar a mistura ar/combustível em tempo real."},
{p:"O que é o 'câmbio automático CVT'?",o:["Câmbio automático com 6 marchas fixas","Transmissão continuamente variável — sem marchas fixas, variação suave de relação","Câmbio manual automatizado","Câmbio com apenas 2 marchas"],c:1,cat:"mecanica",ex:"CVT (Continuously Variable Transmission): transmissão com relação de marcha variável contínua, sem degraus."},
,{p:"A placa com fundo azul e símbolo de tenda indica:",o:["Hotel","Camping","Área de piquenique","Parque estadual"],c:1,cat:"sinalizacao",ex:"I-9: retângulo azul com símbolo de tenda = camping nas proximidades."}
,{p:"Marcas transversais de alerta antes de lombadas servem para:",o:["Indicar faixa de pedestres","Alertar sobre redução de velocidade obrigatória à frente","Marcar início de pista dupla","Indicar cruzamento com prioridade"],c:1,cat:"sinalizacao",ex:"Linhas transversais pré-lombada alertam o motorista para reduzir a velocidade antes da elevação."}
,{p:"O que indica a placa com triângulo amarelo e símbolo de vento lateral?",o:["Ventiladores de túnel","Risco de vento lateral forte na via","Área de pipa proibida","Corredor de ônibus"],c:1,cat:"sinalizacao",ex:"A-30 (Vento Lateral): alerta para vento forte de lado, especialmente perigoso para veículos altos."}
,{p:"Placa retangular verde com nomes de cidades e setas indica:",o:["Proibição de entrada","Indicação de destino e direção para localidades","Área de preservação ambiental","Posto rodoviário à frente"],c:1,cat:"sinalizacao",ex:"Placas verdes de orientação de destino indicam direção e distância para localidades em rodovias."}
,{p:"A diferença entre linha tracejada branca e linha contínua branca é:",o:["A tracejada é mais nova","Tracejada permite mudança de faixa; contínua proíbe","Tracejada é para emergências","Não há diferença prática"],c:1,cat:"sinalizacao",ex:"Tracejada = pode mudar de faixa quando seguro. Contínua = proibido mudar de faixa."}
,{p:"Semáforo com seta verde exclusiva para virar à direita indica:",o:["Verde para todos os movimentos","Verde apenas para quem vai virar à direita — outros devem aguardar","Preferência para pedestres","Fim do ciclo do semáforo"],c:1,cat:"sinalizacao",ex:"Seta verde exclusiva: somente o movimento indicado pela seta está autorizado naquele momento."}
,{p:"A placa 'DÊ A PREFERÊNCIA' (triângulo invertido) é:",o:["Proibição","Advertência","Regulamentação","Indicação"],c:2,cat:"sinalizacao",ex:"R-3 pertence ao grupo R (Regulamentação) — obriga o condutor a ceder passagem."}
,{p:"O que indica a placa com triângulo amarelo e símbolo de cascalho na pista?",o:["Estrada de terra à frente","Cascalho ou pedras soltas na pista — risco de derrapagem","Área de mineração","Proibido veículos com carga"],c:1,cat:"sinalizacao",ex:"A-23 (Cascalho): alerta para pedras soltas que podem causar derrapagem ou danos ao veículo."}
,{p:"Qual a finalidade da placa de 'FIM DE RESTRIÇÃO'?",o:["Indica entrada em área urbana","Cancela a restrição imposta pela placa anterior (velocidade, ultrapassagem, etc.)","Indica fim de rodovia","Permite retorno"],c:1,cat:"sinalizacao",ex:"Placa de fim de restrição cancela a proibição ou limite imposto anteriormente na via."}
,{p:"A placa com 'P' azul e números (ex: 2h) indica:",o:["Proibido estacionar por 2 horas","Estacionamento rotativo permitido por até 2 horas","Zona azul — estacionamento tarifado","Estacionamento somente às 2h"],c:1,cat:"sinalizacao",ex:"Estacionamento regulamentado com limite de tempo. Nas zonas azuis, o condutor usa disco de controle."}
,{p:"O que indica a marcação zebrada (diagonal) em canteiro central ou ilhas?",o:["Pode circular sobre o canteiro","Área de segurança — proibido circular","Estacionamento de emergência","Parada de ônibus"],c:1,cat:"sinalizacao",ex:"Marcação diagonal ou zebrada em ilhas e canteiros: área não circulável, serve como separação."}
,{p:"A placa I-20 (fundo verde, 'SAÍDA DE EMERGÊNCIA' com seta) indica:",o:["Saída de emergência do túnel ou área de risco","Saída para o acostamento","Desvio de obra","Início de rodovia"],c:0,cat:"sinalizacao",ex:"I-20: em túneis indica a posição da saída de emergência para uso em incêndio ou acidente."}
,{p:"O que é a 'sinalização dinâmica' ou 'painel de mensagem variável'?",o:["Placas que piscam sempre","Sinalização eletrônica que pode mudar mensagens conforme a situação do tráfego","Semáforos inteligentes","Sinalização em obras"],c:1,cat:"sinalizacao",ex:"PMVs (Painéis de Mensagem Variável): mostram informações atualizadas sobre velocidade, congestionamento, etc."}
,{p:"A placa de altura máxima mostra:",o:["A altura do viaduto ou obstáculo","A altura máxima do veículo para passar com segurança","A altitude da via","A altura mínima do veículo"],c:1,cat:"sinalizacao",ex:"Exemplo: placa '4,4m' = veículos com mais de 4,4 m de altura não devem passar por aquele ponto."}
,{p:"Qual a cor das marcas de pedestres no pavimento?",o:["Amarelo","Vermelho","Branco","Azul"],c:2,cat:"sinalizacao",ex:"Faixas de pedestres são sempre brancas no pavimento (linhas transversais paralelas)."}
,{p:"Em cruzamento com semáforo e placa PARE, prevalece:",o:["A placa PARE sempre","O semáforo quando estiver operando, caso contrário a placa PARE","A placa sempre","O condutor decide"],c:1,cat:"sinalizacao",ex:"Semáforo operando substitui a placa PARE. Se o semáforo estiver apagado, a placa PARE rege a parada."}
,{p:"A placa A-5 (triângulo com cruz de ruas) indica:",o:["Hospital à frente","Cruzamento à frente","Igreja à frente","Dois desvios possíveis"],c:1,cat:"sinalizacao",ex:"A-5 (Interseção em Cruz): triângulo amarelo com símbolo de cruzamento = cruzamento à frente."}
,{p:"O sinal de 'DESVIO' obrigatório tem forma:",o:["Triangular amarela","Circular azul com seta","Retangular verde","Quadrada branca"],c:1,cat:"sinalizacao",ex:"E-5 (Desvio Obrigatório): círculo azul com seta indicando o desvio a ser seguido."}
,{p:"Qual placa indica que pedestres devem usar a calçada obrigatoriamente?",o:["Placa R-19 (proibido circulação de pedestres na pista)","Placa I-4 (faixa de pedestres)","Placa R-29 (pedestre — calçada obrigatória)","Placa A-19 (pedestres na pista)"],c:2,cat:"sinalizacao",ex:"R-29: círculo azul com pedestre na calçada = circulação obrigatória pela calçada."}
,{p:"Em obras noturnas, a sinalização deve incluir obrigatoriamente:",o:["Apenas cones","Cones, cavaletes e dispositivos luminosos ou refletivos","Apenas placas","Apenas trabalhadores com coletes"],c:1,cat:"sinalizacao",ex:"Obras noturnas exigem dispositivos luminosos ou refletivos (luz, tachão, placa refletiva) para visibilidade."}
,{p:"Qual é o percentual mínimo de aprovação na prova de legislação do DETRAN?",o:["60%","70%","75%","80%"],c:1,cat:"legislacao",ex:"70% = 21 questões corretas de 30. Exigido tanto na prova teórica quanto na prática."}
,{p:"A CNH do condutor com mais de 70 anos tem validade de quantos anos?",o:["1 ano","2 anos","3 anos","5 anos"],c:2,cat:"legislacao",ex:"CTB Art. 159: condutores acima de 70 anos renovam a CNH a cada 3 anos."}
,{p:"O que é necessário para renovar a CNH?",o:["Apenas pagar a taxa","Exame médico e psicológico + taxa de renovação","Nova prova teórica e prática","Apenas exame de vista"],c:1,cat:"legislacao",ex:"Renovação da CNH: exame médico (acuidade visual, saúde física/mental) e exame psicotécnico."}
,{p:"Em qual caso o veículo pode ser apreendido pelo agente de trânsito?",o:["Apenas em caso de acidente","Condutor sem CNH, licenciamento vencido, veículo adulterado, entre outros","Apenas por excesso de velocidade","Apenas se o condutor se recusar a parar"],c:1,cat:"legislacao",ex:"CTB Art. 270: o veículo pode ser retido em diversas situações: sem CNH, irregularidades, etc."}
,{p:"O que significa 'trânsito' conforme o CTB?",o:["Apenas o movimento de veículos","Uso das vias apenas por veículos motorizados","Uso das vias públicas por pessoas, veículos e animais, isolados ou em grupos","Apenas o tráfego em áreas urbanas"],c:2,cat:"legislacao",ex:"CTB Art. 1°: trânsito é o uso das vias por pessoas, veículos e animais — todos têm direitos e deveres."}
,{p:"O diretor de trânsito de um município é vinculado:",o:["Ao DETRAN estadual","Ao órgão executivo de trânsito do município (geralmente Secretaria de Trânsito)","Ao CONTRAN","À Polícia Militar"],c:1,cat:"legislacao",ex:"Municípios com órgão de trânsito estruturado têm autonomia para fiscalizar e legislar no âmbito local."}
,{p:"A Polícia Rodoviária Federal (PRF) tem competência:",o:["Apenas em rodovias estaduais","Nas rodovias federais","Em qualquer via do país","Apenas em São Paulo e Rio"],c:1,cat:"legislacao",ex:"PRF: patrulhamento e fiscalização nas rodovias e estradas federais do Brasil."}
,{p:"Para obter a CNH, quantas etapas de habilitação existem?",o:["2 etapas","3 etapas","4 etapas","5 etapas"],c:2,cat:"legislacao",ex:"4 etapas: 1) Registro; 2) Curso teórico + prova; 3) Curso prático + prova; 4) Emissão da PPD e posterior CNH."}
,{p:"O 'recall' obrigatório de veículo com defeito de fábrica deve ser feito:",o:["Pelo comprador, por conta própria","Pelo fabricante, gratuitamente","Pelo DETRAN mediante taxa","Apenas se o defeito causar acidente"],c:1,cat:"legislacao",ex:"Recall: o fabricante é obrigado a corrigir defeitos de fábrica gratuitamente. Ignorar o recall é infração."}
,{p:"A lei seca no trânsito brasileiro é popularmente chamada de:",o:["Lei do Bafômetro","Lei Seca","Lei Renato Welter (9.503/97 — CTB)","Lei 11.705/08"],c:3,cat:"legislacao",ex:"A Lei 11.705/2008 (Lei Seca) estabeleceu tolerância zero de álcool para condutores no Brasil."}
,{p:"Qual o prazo mínimo de suspensão da CNH por acumular 20 pontos?",o:["30 dias","6 meses","1 mês","Depende do tipo de infração"],c:1,cat:"legislacao",ex:"CTB Art. 261: ao atingir 20 pontos em 12 meses, a CNH é suspensa por no mínimo 6 meses."}
,{p:"O veículo pode circular com para-brisa trincado?",o:["Sim, se for pequena trinca","Não — é infração média","Sim, se for na lateral","Sim se tiver passado na inspeção veicular recentemente"],c:1,cat:"legislacao",ex:"CTB Art. 230: para-brisa em mau estado de conservação que prejudique a visibilidade = média (4 pontos)."}
,{p:"Qual o limite máximo de passageiros em veículo da categoria B?",o:["4 passageiros","7 passageiros","8 passageiros","Não há limite"],c:2,cat:"legislacao",ex:"Categoria B: veículos com capacidade de até 8 passageiros e PBT até 3.500 kg."}
,{p:"Transportar carga fora das dimensões legais exige:",o:["Nenhuma providência especial","Autorização especial de trânsito (AET) + sinalização","Apenas aviso ao DETRAN","Somente escolta policial"],c:1,cat:"legislacao",ex:"Cargas especiais (excesso de dimensão/peso): precisam de AET, sinalização, escolta e horários específicos."}
,{p:"Conduzir veículo com CNH vencida há menos de 30 dias é:",o:["Permitido temporariamente","Infração grave — 5 pontos","Infração gravíssima — 7 pontos","Apenas advertência"],c:1,cat:"legislacao",ex:"CTB Art. 162, III: conduzir com CNH vencida = infração grave, independente do tempo de vencimento."}
,{p:"O que é o 'B.O. amigável' em caso de acidente sem vítimas?",o:["Boletim Oficial da polícia","Formulário preenchido pelos próprios condutores documentando o acidente","Acordo verbal sem documentação","Notificação enviada ao seguro"],c:1,cat:"legislacao",ex:"Formulário de comunicação de acidente (CPA) preenchido pelos envolvidos quando não há vítimas."}
,{p:"O velomotor pode ser conduzido por quem tem:",o:["CNH de qualquer categoria","ACC ou CNH categoria A","Somente CNH categoria B","Apenas maiores de 21 anos"],c:1,cat:"legislacao",ex:"Velomotor (motor entre 50 cc e 150 cc) exige ACC ou CNH categoria A (ou B com adicional)."}
,{p:"Em caso de furto do veículo, o proprietário deve:",o:["Comunicar ao seguro e aguardar","Registrar B.O., comunicar ao DETRAN e ao seguro","Apenas comunicar ao seguro","Aguardar 30 dias antes de registrar B.O."],c:1,cat:"legislacao",ex:"Furto/roubo: registre B.O. imediatamente. Comunique ao DETRAN para bloqueio e ao seguro para cobertura."}
,{p:"O condutor pode ser preso em flagrante por qual infração de trânsito?",o:["Excesso de velocidade","Avançar sinal vermelho","Dirigir embriagado acima de 0,33 mg/L (crime)","Estacionar em local proibido"],c:2,cat:"legislacao",ex:"CTB Art. 306: embriaguez ao volante acima de 0,33 mg/L = crime. Admite prisão em flagrante."}
,{p:"Qual documento o condutor deve apresentar quando abordado por agente de trânsito?",o:["Apenas a CNH","CNH e CRLV do veículo","CNH, CRLV e comprovante de seguro","Apenas o CRLV"],c:1,cat:"legislacao",ex:"O condutor deve apresentar CNH (ou PPD) e CRLV do veículo quando solicitado pelo agente."}
,{p:"Qual a penalidade para quem furar fila em cruzamentos usando o acostamento?",o:["Leve","Média","Grave","Gravíssima"],c:3,cat:"legislacao",ex:"Usar o acostamento para furar fila = gravíssima, 7 pontos (uso indevido do acostamento)."}
,{p:"Deixar de sinalizar o veículo parado na via (triângulo) é infração:",o:["Leve","Média","Grave","Não é infração se for por menos de 30 min"],c:1,cat:"infrações",ex:"CTB Art. 254, II: não sinalizar veículo parado na via = média, 4 pontos."}
,{p:"Circular com veículo com farol traseiro apagado à noite é infração:",o:["Leve","Média","Grave","Não é infração"],c:0,cat:"infrações",ex:"CTB Art. 230: farol traseiro com defeito = leve, 3 pontos."}
,{p:"Qual é a infração por abandonar veículo em via pública?",o:["Leve","Média","Grave","Não é infração"],c:1,cat:"infrações",ex:"CTB Art. 252: abandonar veículo em via pública = média, 4 pontos."}
,{p:"Transitar em velocidade incompatível com o local (escola, hospital) é infração:",o:["Leve","Média","Grave","Gravíssima com fator multiplicador"],c:2,cat:"infrações",ex:"CTB Art. 218 combinado com locais sensíveis: velocidade inadequada nestes locais = grave ou agravada."}
,{p:"Não respeitar a preferência na rotatória é infração:",o:["Leve","Média","Grave","Gravíssima"],c:2,cat:"infrações",ex:"CTB Art. 186: desrespeitar preferência em rotatória = grave, 5 pontos."}
,{p:"Dirigir com carteira de habilitação de outra categoria (ex.: usando CNH A para conduzir carro) é:",o:["Permitido temporariamente","Infração como se não tivesse CNH","Multa leve","Apenas advertência"],c:1,cat:"infrações",ex:"Conduzir veículo de categoria diferente da habilitada = equivale a dirigir sem habilitação (gravíssima)."}
,{p:"Qual a infração por não usar cinto de segurança nos bancos traseiros?",o:["Não é infração","Leve","Grave — 5 pontos","Depende do tipo de veículo"],c:2,cat:"infrações",ex:"O cinto é obrigatório em todos os bancos. Infração grave (5 pontos) para cada ocupante sem cinto."}
,{p:"Conduzir veículo com tacógrafo violado (caminhoneiros) é infração:",o:["Leve","Média","Grave","Gravíssima"],c:3,cat:"infrações",ex:"CTB Art. 230, XIX: tacógrafo com lacre violado, defeituoso ou adulterado = gravíssima, 7 pontos."}
,{p:"Parar o veículo em fila dupla por mais de 2 minutos é infração:",o:["Não é infração se breve","Leve","Média","Grave"],c:2,cat:"infrações",ex:"CTB Art. 181: parar o veículo em fila dupla por tempo superior ao permitido = grave, 5 pontos."}
,{p:"Usar farol alto em via com iluminação pública suficiente é infração:",o:["Leve","Não é infração","Média","Grave"],c:0,cat:"infrações",ex:"CTB Art. 250: uso de farol alto onde não necessário ofusca outros = leve, 3 pontos."}
,{p:"Não dar seta ao mudar de faixa é infração:",o:["Leve","Média","Grave","Não é infração"],c:1,cat:"infrações",ex:"CTB Art. 241: deixar de sinalizar mudança de faixa = média, 4 pontos."}
,{p:"Circular com veículo com extintor vencido é infração:",o:["Não é infração","Leve","Média","Grave"],c:2,cat:"infrações",ex:"CTB Art. 230, XI: extintor vencido ou ausente = grave, 5 pontos (item de segurança obrigatório)."}
,{p:"Conduzir veículo com vidros tintados (insulfilm) acima do permitido é infração:",o:["Não é infração","Leve","Média","Grave"],c:1,cat:"infrações",ex:"CTB Art. 230, III: insulfilm além do limite legal obstrui visibilidade = leve, 3 pontos."}
,{p:"Qual a infração por jogar lixo na via?",o:["Não é infração de trânsito","Leve","Média","Grave"],c:1,cat:"infrações",ex:"CTB Art. 252, XI: jogar objetos ou substâncias na via = média, 4 pontos."}
,{p:"Transportar criança no colo do passageiro dianteiro é infração:",o:["Permitido até 2 anos","Grave","Gravíssima","Leve"],c:2,cat:"infrações",ex:"CTB Art. 168: criança no colo = gravíssima, 7 pontos. Crianças devem usar dispositivo de retenção."}
,{p:"Estacionar em área reservada a táxis sem autorização é infração:",o:["Leve","Média","Grave","Gravíssima"],c:3,cat:"infrações",ex:"CTB Art. 181, XII: estacionar em área reservada a táxis ou outros = gravíssima, 7 pontos + remoção."}
,{p:"Fazer conversão proibida pela sinalização é infração:",o:["Leve","Média","Grave","Gravíssima"],c:2,cat:"infrações",ex:"CTB Art. 185: fazer conversão proibida pela sinalização = grave, 5 pontos."}
,{p:"Qual a punição para quem dirige embriagado e causa morte?",o:["Apenas multa e cassação da CNH","Homicídio culposo agravado — reclusão de 2 a 4 anos + cassação + multa","Detenção de 6 meses","Apenas suspensão da CNH por 2 anos"],c:1,cat:"infrações",ex:"CTB Art. 302, §3°: homicídio culposo sob efeito de álcool = pena agravada de 2 a 4 anos de reclusão."}
,{p:"Parar em cima da linha de pedestre no semáforo é infração:",o:["Não é infração","Leve","Média","Grave"],c:2,cat:"infrações",ex:"CTB Art. 181, IX: parar sobre a faixa de pedestres aguardando o sinal = média, 4 pontos."}
,{p:"Qual a multa base de uma infração grave?",o:["R$ 88,38","R$ 130,16","R$ 195,23","R$ 293,47"],c:2,cat:"infrações",ex:"Infração grave = multa base de R$ 195,23 + 5 pontos na CNH."}
,{p:"Qual a multa base de uma infração leve?",o:["R$ 88,38","R$ 130,16","R$ 195,23","R$ 293,47"],c:0,cat:"infrações",ex:"Infração leve = multa base de R$ 88,38 + 3 pontos na CNH."}
,{p:"Transitar pela faixa exclusiva de ônibus de moto sem autorização é:",o:["Permitido para motos","Grave — 5 pontos","Leve","Gravíssima — 7 pontos"],c:1,cat:"infrações",ex:"CTB Art. 198: qualquer veículo não autorizado (inclusive moto) na faixa exclusiva = grave, 5 pontos."}
,{p:"Qual a infração por dirigir com CNH vencida há mais de 30 dias?",o:["Leve","Média","Grave","Gravíssima — equivale a não ter CNH"],c:3,cat:"infrações",ex:"CNH vencida há mais de 30 dias = gravíssima (equivale a não habilitado), 7 pontos + retenção."}
,{p:"Qual a penalidade para quem avança a cancela do pedágio sem pagar?",o:["Leve","Média","Grave","Gravíssima"],c:2,cat:"infrações",ex:"CTB Art. 209: não pagar pedágio e forçar a cancela = grave, 5 pontos + multa específica."}
,{p:"Circular com veículo emitindo fumaça preta excessiva é infração:",o:["Não é infração de trânsito","Leve","Média","Grave"],c:2,cat:"infrações",ex:"CTB Art. 231, VI: emissão de poluentes acima do permitido = grave, 5 pontos."}
,{p:"Não dar passagem a veículo de emergência com sirene ligada é infração:",o:["Leve","Média","Grave","Gravíssima"],c:2,cat:"infrações",ex:"CTB Art. 196: não ceder passagem a veículos de emergência (bombeiro, ambulância, polícia) = grave, 5 pontos."}
,{p:"Fotografar o agente de trânsito durante abordagem é:",o:["Proibido — grave infração","Permitido — é um direito do cidadão","Proibido apenas à noite","Permitido apenas com autorização"],c:1,cat:"infrações",ex:"Fotografar ou gravar agentes públicos no exercício da função em espaço público é um direito do cidadão."}
,{p:"Qual a infração por estacionar em frente a entrada de garagem?",o:["Leve","Média","Grave","Gravíssima"],c:2,cat:"infrações",ex:"CTB Art. 181, I: estacionar na frente de garagens = grave, 5 pontos + remoção."}
,{p:"Moto circulando entre faixas em velocidade acima de 50 km/h é:",o:["Permitido em congestionamento","Proibido — infração grave","Permitido em qualquer velocidade","Apenas proibido em rodovias"],c:1,cat:"infrações",ex:"CTB: motocicletas podem transitar entre faixas (filtering), mas apenas em velocidade baixa e com segurança."}
,{p:"Qual a infração por reboque ou empurrão sem equipamento adequado?",o:["Leve","Média","Grave","Não é infração"],c:1,cat:"infrações",ex:"CTB Art. 252, III: rebocar veículo sem o equipamento regulamentar (cabo, barra) = média, 4 pontos."}
,{p:"A principal causa de acidentes em rodovias no Brasil é:",o:["Falha mecânica","Pista em mau estado","Erro humano (excesso de velocidade, distração, alcoolismo)","Sinalização inadequada"],c:2,cat:"direcao",ex:"Mais de 90% dos acidentes de trânsito têm o fator humano como causa principal."}
,{p:"A técnica 'IPDE' na direção defensiva significa:",o:["Identificar, Prever, Decidir, Executar","Indicar, Parar, Desviar, Evitar","Inspecionar, Planejar, Dirigir, Estacionar","Iniciar, Progredir, Diminuir, Estacionar"],c:0,cat:"direcao",ex:"IPDE: Identificar perigos, Prever consequências, Decidir a ação, Executar a manobra."}
,{p:"Ao perceber que um veículo à frente freou bruscamente e você não consegue frear, deve:",o:["Fechar os olhos","Tentar desviar para o acostamento ou para a faixa ao lado se livre","Buzinar intensamente","Ligar os 4 piscas"],c:1,cat:"direcao",ex:"Se inevitável: tente desviar para área menos perigosa. Reduzir a intensidade do impacto salva vidas."}
,{p:"Em qual situação é PROIBIDO ultrapassar?",o:["Em reta com visibilidade","Em curva sem visibilidade","Em rodovia com 3 faixas","Em estrada com velocidade máxima de 60 km/h"],c:1,cat:"direcao",ex:"CTB Art. 35: proibido ultrapassar em curvas, lombadas, cruzamentos sem visibilidade, e pontes."}
,{p:"Ao guiar na chuva intensa, deve-se:",o:["Manter a mesma velocidade, o carro é seguro","Reduzir a velocidade, ligar farol baixo e aumentar a distância","Acelerar para sair da chuva logo","Usar somente o freio de mão"],c:1,cat:"direcao",ex:"Chuva intensa reduz visibilidade e aderência. Reduza, ligue farol baixo e aumente distância de segurança."}
,{p:"Como deve ser feita a frenagem com ABS?",o:["Bombear o pedal alternadamente","Pisar firme e manter pressão constante no pedal","Usar somente o freio de mão","Usar o freio lentamente e gradualmente"],c:1,cat:"direcao",ex:"Com ABS: pise forte e mantenha. O sistema impede o travamento automaticamente. Não bombeie o pedal."}
,{p:"Ao ultrapassar caminhão, por onde se deve passar?",o:["Pelo lado esquerdo do caminhão","Pelo lado direito do caminhão","Por qualquer lado dependendo da via","Apenas pelo acostamento"],c:0,cat:"direcao",ex:"Sempre pela esquerda do veículo ultrapassado. Ultrapassagem pela direita só é permitida em exceções específicas."}
,{p:"Qual a atitude correta ao receber a sinalização de ultrapassagem de uma moto?",o:["Acelerar","Manter a velocidade e não mudar de faixa abruptamente","Fechar a moto","Buzinar e fechar a janela"],c:1,cat:"direcao",ex:"Facilite a ultrapassagem. Não mude de velocidade bruscamente e mantenha a trajetória reta."}
,{p:"Em vias com várias faixas, qual faixa deve usar o veículo mais lento?",o:["A do meio","A da esquerda","A da direita","Qualquer faixa — é indiferente"],c:2,cat:"direcao",ex:"CTB: manter-se na faixa da direita é obrigação. A esquerda é para ultrapassagem."}
,{p:"Qual o principal risco ao ultrapassar em rodovias de pista simples?",o:["Multa","Acidente frontal com veículo em sentido contrário","Perda do controle do veículo","Problemas com o motor"],c:1,cat:"direcao",ex:"O principal perigo é a colisão frontal. É preciso visibilidade total e espaço para completar a manobra."}
,{p:"Ao entrar em via preferencial, o condutor deve:",o:["Acenar e entrar","Frear somente na via preferencial","Reduzir, verificar o fluxo e entrar com segurança cedendo preferência","Entrar rapidamente para não atrapalhar"],c:2,cat:"direcao",ex:"Sempre ceda a preferência ao tráfego da via em que vai entrar. Só entre quando seguro."}
,{p:"Qual a importância do tempo de reação na frenagem?",o:["Não influencia na distância","É o tempo entre perceber o perigo e pisar o freio — aumenta a distância total de parada","É ignorado nos veículos modernos","Afeta apenas motos"],c:1,cat:"direcao",ex:"Tempo de reação médio: 0,8 a 1 segundo. A 60 km/h, o carro percorre ~17m antes de frear."}
,{p:"Em rodovias com chuva, a frenagem pode ser até quantas vezes maior?",o:["Igual à pista seca","2 vezes maior","3 vezes maior","5 vezes maior"],c:2,cat:"direcao",ex:"Pista molhada pode triplicar a distância de frenagem. Por isso a velocidade deve ser reduzida."}
,{p:"Ao fazer marcha à ré, o condutor deve:",o:["Usar somente os retrovisores","Verificar pessoalmente os pontos cegos e sinalizar com buzina breve se necessário","Usar somente a câmera de ré","Não é necessário verificar nada se o carro tiver sensor"],c:1,cat:"direcao",ex:"Câmera e sensores auxiliam, mas não substituem a verificação direta. Verifique os pontos cegos."}
,{p:"Qual a conduta ao encontrar um veículo fazendo ultrapassagem e vindo de frente?",o:["Manter a velocidade e forçar o veículo a voltar para a faixa","Reduzir a velocidade e ir para a extremidade direita da pista","Acelerar e buzinar","Ir para o acostamento imediatamente em qualquer caso"],c:1,cat:"direcao",ex:"Reduza e vá para a direita. Dê espaço para o veículo completar a ultrapassagem com segurança."}
,{p:"Em qual situação é correto usar o pisca-alerta durante o deslocamento?",o:["Para agradecer outros condutores","Para avisar que vai dobrar","Nunca em movimento — apenas parado","Em emergências ou quando o veículo está se deslocando muito abaixo da velocidade normal (avaria)"],c:3,cat:"direcao",ex:"Pisca-alerta em movimento: apenas em emergências ou quando trafegar abaixo da velocidade normal."}
,{p:"O que é a 'faixa de segurança' ao estacionar?",o:["Faixa amarela junto à guia","Distância mínima a manter de esquinas, hidrantes e entradas de garagem","Limite entre a calçada e a pista","Zona de estacionamento rotativo"],c:1,cat:"direcao",ex:"Distâncias mínimas ao estacionar: 5m de esquinas, 5m de hidrantes, 1m de entradas de garagem."}
,{p:"Em trechos de pista molhada, a velocidade recomendada é:",o:["A mesma da pista seca","20% abaixo do limite","30% abaixo do limite","50% abaixo do limite"],c:1,cat:"direcao",ex:"Condição geral: reduza cerca de 20% em pista molhada. Em névoa ou neblina, reduza ainda mais."}
,{p:"A 'zona de perigo' de um caminhão inclui:",o:["Apenas a parte de trás","Os 4 lados do veículo — especialmente lateral direita, traseira e frente","Apenas a frente","Apenas os lados"],c:1,cat:"direcao",ex:"Caminhões têm pontos cegos nos 4 lados. Fique visível nos espelhos ou se afaste."}
,{p:"Por que é perigoso dirigir com o banco muito reclinado?",o:["Prejudica a visão do painel","Reduz controle do volante, do freio e do acelerador — reação mais lenta","Não é perigoso","Apenas desconfortável"],c:1,cat:"direcao",ex:"Banco reclinado = braços esticados, reação lenta, menos força no volante. Mantenha o banco ereto."}
,{p:"Em cruzamento sem sinalização, com dois veículos chegando ao mesmo tempo, a preferência é:",o:["De quem chegou primeiro","De quem vem pela direita","Do veículo maior","Do veículo que vem em maior velocidade"],c:1,cat:"direcao",ex:"CTB Art. 29: sem sinalização, a preferência é de quem vem pela direita do condutor que está aguardando."}
,{p:"Ao fazer a manobra de estacionamento em paralelo, a sequência correta é:",o:["Avançar e entrar direto na vaga","Parar paralelo ao carro da frente, fazer marcha à ré em ângulo e corrigir","Fazer a vaga pela frente sempre","Qualquer método é igualmente correto"],c:1,cat:"direcao",ex:"Estacionamento paralelo: alinhe, recue em ângulo para dentro da vaga, corrija a posição."}
,{p:"Em descidas longas, os freios podem superaquecer causando o fenômeno:",o:["Aquaplanagem","Fading (perda de eficiência dos freios por superaquecimento)","Shimmy","Torque steer"],c:1,cat:"direcao",ex:"Fading: freios superaquecidos perdem eficiência. Use o freio motor (marcha baixa) em descidas."}
,{p:"A manobra de 'baliza' (vaga perpendicular) deve ser realizada:",o:["Acelerando e entrando rápido","Com velocidade muito baixa, verificando os pontos cegos","Usando somente a câmera de ré","Sem usar os retrovisores laterais"],c:1,cat:"direcao",ex:"Baliza: velocidade baixa, verificação completa dos pontos cegos e referências visuais precisas."}
,{p:"Ao aproximar-se de um pedestre que está na calçada próximo à faixa:",o:["Manter velocidade normal — só para quem já está na faixa","Reduzir a velocidade e estar preparado para ceder passagem","Buzinar para avisar","Acelerar para passar antes"],c:1,cat:"direcao",ex:"Boa prática: reduza ao ver pedestre próximo à faixa. O pedestre tem preferência ao entrar na faixa."}
,{p:"Em condições de gelo ou neve na pista, a velocidade deve ser reduzida em:",o:["10%","20%","50% ou mais","Não há necessidade de redução se o carro tiver tração 4x4"],c:2,cat:"direcao",ex:"Gelo/neve reduz dramaticamente a aderência. Reduza pelo menos 50% e use marchas baixas."}
,{p:"A 'viagem segura' em rodovias inclui:",o:["Apenas respeitar os limites de velocidade","Planejar a rota, revisar o veículo, respeitar a sinalização e descansar a cada 4h","Apenas não beber","Apenas usar o cinto"],c:1,cat:"direcao",ex:"Viagem segura: planejamento + veículo revisado + sinalização respeitada + pausas a cada 4h."}
,{p:"A principal medida para prevenir acidentes com pedestres em área urbana é:",o:["Buzinar sempre ao se aproximar","Reduzir a velocidade e ceder sempre que houver pedestres próximos","Aumentar a iluminação do veículo","Usar o farol alto"],c:1,cat:"seguranca",ex:"Velocidade compatível + atenção constante a pedestres são as principais medidas preventivas."}
,{p:"O que é 'colisão traseira' e como evitá-la?",o:["Colisão pela frente — evite freando bruscamente","Colisão pela traseira — evite mantendo distância de segurança adequada","Colisão lateral — evite usando espelhos","Colisão em cruzamento — evite olhando nos dois lados"],c:1,cat:"seguranca",ex:"Colisão traseira: você bate no veículo à frente. Prevenção: distância de segurança suficiente."}
,{p:"Qual o correto posicionamento do cinto de segurança?",o:["Travessa o peito e passa pelo pescoço","Parte superior sobre o ombro e clavícula, inferior pelo quadril","Passar apenas pela cintura","Parte superior pelo pescoço para mais conforto"],c:1,cat:"seguranca",ex:"Cinto correto: parte superior sobre o ombro (não no pescoço), inferior sobre o quadril (não ventre)."}
,{p:"Quais são os três pilares da direção segura?",o:["Velocidade, atenção e sinalização","Conhecimento, habilidade e atitude","Cinto, air bag e ABS","Visibilidade, sinalização e velocidade"],c:1,cat:"seguranca",ex:"Os 3 pilares da direção segura: Conhecimento (das leis e técnicas), Habilidade (prática) e Atitude (comportamento)."}
,{p:"Em caso de acidente com vítima presa no veículo, deve-se:",o:["Puxar a vítima imediatamente","Aguardar socorro especializado (bombeiros) para retirar a vítima com segurança","Quebrar o vidro e arrastar","Dar respiração boca a boca dentro do carro"],c:1,cat:"seguranca",ex:"Vítima presa: só mova se houver risco imediato (fogo, afogamento). Aguarde o Corpo de Bombeiros."}
,{p:"O que é o 'ponto de impacto' em um acidente?",o:["O local onde o veículo parou após o acidente","O local exato onde dois veículos colidiram","O dano ao veículo","O ponto mais fraco da estrutura do veículo"],c:1,cat:"seguranca",ex:"Ponto de impacto: local exato da colisão, importante para análise pericial e determinação de responsabilidades."}
,{p:"Em caso de desconforto ou mal-estar ao volante, o condutor deve:",o:["Continuar se o destino for próximo","Parar em local seguro imediatamente","Abrir a janela e continuar","Acelerar para chegar logo e descansar"],c:1,cat:"seguranca",ex:"Qualquer desconforto (tontura, visão turva, dor) exige parada imediata. Dirigir doente é perigoso."}
,{p:"Como o estresse afeta a condução?",o:["Não tem impacto","Aumenta os reflexos","Prejudica o julgamento, aumenta a agressividade e distrai o condutor","Melhora o foco"],c:2,cat:"seguranca",ex:"Estresse afeta negativamente: reduz a tolerância, piora o julgamento e aumenta comportamentos de risco."}
,{p:"A cadeirinha infantil deve ser instalada no banco traseiro porque:",o:["É uma preferência pessoal","O airbag dianteiro pode causar lesões fatais em crianças pequenas","O banco dianteiro não tem cinto de 3 pontos","Apenas por questões de espaço"],c:1,cat:"seguranca",ex:"O airbag dianteiro, ao disparar, pode causar lesões graves em crianças. Sempre use o banco traseiro."}
,{p:"O que faz o pneu estepe calibrado evitar em viagens longas?",o:["Pneu estepe não precisa ser calibrado","Evita que você fique parado em caso de furo sem poder trocar o pneu","Serve como peso para melhor estabilidade","Reduz o consumo de combustível"],c:1,cat:"seguranca",ex:"Estepe calibrado = segurança em viagens. Verifique a pressão do estepe também a cada 30 dias."}
,{p:"Qual é o risco do uso do celular ao volante além da multa?",o:["Apenas a multa","Aumenta em até 4 vezes o risco de acidente — distração cognitiva","Nenhum risco adicional com viva-voz","O risco é apenas físico ao segurar o aparelho"],c:1,cat:"seguranca",ex:"Celular ao volante (mesmo viva-voz) aumenta 4x o risco de acidente por distração cognitiva."}
,{p:"O que é o 'campo de visão' do condutor e qual sua importância?",o:["A capacidade visual do condutor fora do veículo","A área que o condutor consegue ver — fundamental para perceber perigos com antecedência","A distância que os faróis iluminam","A visão nos espelhos retrovisores"],c:1,cat:"seguranca",ex:"Campo de visão: área visível ao condutor. Velocidade alta reduz o campo. A 100 km/h é muito estreito."}
,{p:"Como o excesso de velocidade afeta o campo de visão?",o:["Não afeta","Amplia o campo de visão","Estreita o campo de visão e reduz o tempo de reação","Melhora a concentração"],c:2,cat:"seguranca",ex:"A 30 km/h, campo ~180°. A 130 km/h, campo reduz para ~40°, criando 'visão em túnel'."}
,{p:"Qual cuidado especial deve-se ter ao dirigir logo após a chuva cessar?",o:["Nenhum — a pista seca rapidamente","Atenção à lama de óleo que fica na superfície da pista quando molha pela primeira vez","Usar farol alto","Acelerar para secar os freios"],c:1,cat:"seguranca",ex:"Nos primeiros minutos de chuva, o óleo acumulado na pista mistura-se com água, tornando-a muito escorregadia."}
,{p:"O que verificar no veículo antes de uma viagem longa?",o:["Apenas o nível de combustível","Pneus (calibragem e condição), óleo, água, luzes, freios e documentos","Apenas os documentos","Apenas a condição dos pneus"],c:1,cat:"seguranca",ex:"Revisão pré-viagem: pneus, óleo, água, luzes, freios, limpadores, documentos e estepe."}
,{p:"Na presença de fumaça em túnel, o correto é:",o:["Sair do carro e correr","Manter-se baixo onde há menos fumaça, sinalizar e sair pela saída de emergência","Ligar o ar condicionado","Permanecer no veículo"],c:1,cat:"seguranca",ex:"Fumaça em túnel: saia baixo (fumaça sobe), sinalize o carro, busque a saída de emergência sinalizando com a mão."}
,{p:"Qual a função do 'cinto de três pontos' em relação ao 'cinto de dois pontos'?",o:["São equivalentes","O cinto de 3 pontos distribui melhor a força do impacto, protegendo o tórax","O cinto de 2 pontos protege melhor o pescoço","O cinto de 2 pontos é mais moderno"],c:1,cat:"seguranca",ex:"Cinto de 3 pontos: retém o corpo em 3 pontos (ombro + quadril), distribuindo a força de impacto."}
,{p:"A menor quantidade de álcool pode comprometer a direção porque:",o:["Apenas quantidades acima de 0,5 g/L afetam a direção","Qualquer quantidade afeta a coordenação, reflexos e julgamento","Apenas quando combinado com medicamentos","Apenas em pessoas não habituadas a beber"],c:1,cat:"seguranca",ex:"Estudos mostram que mesmo pequenas quantidades de álcool comprometem reflexos e julgamento."}
,{p:"O que é o 'efeito de encadeamento' dos faróis?",o:["Faróis com luz LED muito forte","O ofuscamento progressivo causado por múltiplos faróis altos em sequência","O reflexo dos faróis na pista molhada","A sincronização de semáforos em avenida"],c:0,cat:"seguranca",ex:"Encadeamento: múltiplos faróis altos seguidos ofuscam o condutor de forma cumulativa e perigosa."}
,{p:"Em caso de acidente com derramamento de combustível, o que NÃO fazer?",o:["Chamar bombeiros","Desligar o motor","Fumar ou ligar isqueiros nas proximidades","Avisar outros veículos"],c:2,cat:"seguranca",ex:"Combustível derramado pode inflamar a qualquer faísca. Proibido fumar, ligar isqueiros ou fazer faíscas."}
,{p:"A revisão dos freios deve ser feita:",o:["Apenas quando o pedal ficar mole","A cada 10.000 km ou conforme o manual do proprietário","Apenas quando houver barulho","Somente na inspeção veicular anual"],c:1,cat:"seguranca",ex:"Freios: revisão periódica conforme o manual. Não espere sintomas — prevenção evita acidentes."}
,{p:"Quais são os maiores fatores de risco para jovens condutores (18-24 anos)?",o:["Falta de habilidade técnica apenas","Inexperiência, excesso de velocidade, uso de álcool e uso do celular","Apenas o excesso de velocidade","Sonolência e fadiga"],c:1,cat:"seguranca",ex:"Jovens têm maior risco pela combinação de inexperiência, comportamento de risco e distração digital."}
,{p:"O seguro obrigatório DPVAT cobre:",o:["Danos materiais ao veículo","Danos pessoais (morte e invalidez) causados a qualquer vítima de acidente","Roubo do veículo","Danos a propriedades terceiras"],c:1,cat:"seguranca",ex:"DPVAT: cobertura exclusiva para danos pessoais (morte, invalidez permanente, despesas médicas)."}
,{p:"Qual a função do catalisador no sistema de escapamento?",o:["Aumentar a potência","Converter gases poluentes em compostos menos prejudiciais ao ambiente","Reduzir o ruído do motor","Aumentar a eficiência do combustível"],c:1,cat:"mecanica",ex:"Catalisador: converte HC, CO e NOx em CO2, H2O e N2 menos prejudiciais. Obrigatório por lei."}
,{p:"O que causa o barulho de 'clic-clic' ao virar o volante em curvas fechadas?",o:["Alternador","Homocinética (junta homocinética) desgastada","Filtro de ar","Amortecedor"],c:1,cat:"mecanica",ex:"Clique ao virar o volante = junta homocinética desgastada. Pode partir e travar a roda."}
,{p:"O que é o sistema 'injeção direta'?",o:["Injeção de combustível no coletor de admissão","Injeção de combustível diretamente na câmara de combustão do cilindro","Sistema de injeção de ar","Injeção de óleo para lubrificação"],c:1,cat:"mecanica",ex:"Injeção direta: combustível injetado direto no cilindro, maior eficiência e menor consumo."}
,{p:"O que indica barulho de 'clanking' (pancadas) ao acelerar?",o:["Pneu furado","Possível problema no motor (biela, pistão) ou no sistema de escapamento solto","Embreagem desgastada","Freios com problema"],c:1,cat:"mecanica",ex:"Pancadas no motor ao acelerar podem indicar problemas graves (biela, pistão) — revisão urgente."}
,{p:"A função do servo-freio (booster) é:",o:["Aplicar os freios automaticamente","Amplificar a força aplicada pelo condutor no pedal de freio","Controlar o ABS","Acionar o freio de estacionamento"],c:1,cat:"mecanica",ex:"Servo-freio: usa vácuo do motor para multiplicar a força do pedal, reduzindo o esforço necessário."}
,{p:"O que é a 'convergência' dos pneus (alinhamento)?",o:["Calibragem dos pneus","Ângulo dos pneus em relação ao eixo longitudinal do veículo","Balanceamento das rodas","Rodízio dos pneus"],c:1,cat:"mecanica",ex:"Convergência (toe): ângulo que as rodas fazem vistas de cima. Afeta desgaste dos pneus e direção."}
,{p:"Com que frequência deve-se fazer o rodízio dos pneus?",o:["A cada 5.000 km","A cada 10.000 km","A cada 20.000 km","Apenas quando houver desgaste irregular"],c:1,cat:"mecanica",ex:"Rodízio a cada 10.000 km garante desgaste uniforme e prolonga a vida dos 4 pneus."}
,{p:"O que indica consumo de óleo pelo motor (fumaça azul no escapamento)?",o:["Motor novo funcionando normalmente","Desgaste nos anéis do pistão ou guias de válvulas — revisão necessária","Falta de refrigerante","Problema no catalisador"],c:1,cat:"mecanica",ex:"Fumaça azul = óleo sendo queimado junto com o combustível. Indica desgaste interno do motor."}
,{p:"O que é o 'balanceamento' das rodas?",o:["Calibrar a pressão dos pneus","Distribuir o peso uniformemente na roda para eliminar vibrações","Alinhar as rodas","Verificar a profundidade do sulco"],c:1,cat:"mecanica",ex:"Balanceamento: pequenos pesos são adicionados à roda para equilibrá-la, evitando vibrações em alta velocidade."}
,{p:"O que causa fumaça branca espessa no escapamento (não no arranque frio)?",o:["Combustível em excesso","Líquido de arrefecimento sendo queimado — possível junta do cabeçote com problema","Óleo queimado","Motor novo em período de amaciamento"],c:1,cat:"mecanica",ex:"Fumaça branca densa e contínua = refrigerante entrando no cilindro. Possível junta do cabeçote gasta."}
,{p:"Qual a função dos amortecedores?",o:["Suportar o peso do veículo","Controlar os movimentos das molas e manter os pneus em contato com a pista","Reduzir o consumo de combustível","Controlar a direção"],c:1,cat:"mecanica",ex:"Amortecedores (estabilizadores de choque): controlam as oscilações das molas, mantendo contato com o piso."}
,{p:"O que é o 'sistema common rail'?",o:["Sistema de arrefecimento","Sistema de injeção de alta pressão para motores diesel","Sistema de transmissão automática","Sistema de direção hidráulica"],c:1,cat:"mecanica",ex:"Common rail: sistema de injeção direta de alta pressão para diesel, com injetor individual por cilindro."}
,{p:"Quando a luz de óleo pisca durante a condução, significa:",o:["Nível de óleo próximo da reserva — completar em breve","Pressão de óleo baixa — PARE IMEDIATAMENTE","Óleo sujo — trocar em breve","Temperatura do óleo alta"],c:1,cat:"mecanica",ex:"Luz de óleo piscando em movimento = perda de pressão de óleo. PARE imediatamente para evitar dano grave."}
,{p:"A correia dentada (ou corrente) do motor serve para:",o:["Acionar o alternador","Sincronizar a abertura das válvulas com o movimento do pistão","Acionar a bomba d'água apenas","Acionar o compressor do ar condicionado"],c:1,cat:"mecanica",ex:"Correia dentada: sincroniza o eixo do virabrequim com o eixo de cames (válvulas). Quebrar causa dano grave."}
,{p:"O que é o fluido de direção hidráulica e quando trocar?",o:["Óleo do câmbio — trocar a cada 30.000 km","Fluido viscoso que transmite pressão na direção — trocar conforme o manual (30-60.000 km)","Líquido de freio — trocar anualmente","Fluido do sistema de arrefecimento"],c:1,cat:"mecanica",ex:"Fluido de direção: transmite pressão da bomba para o sistema de direção. Troque conforme o manual."}
,{p:"Qual é o indicativo de que o filtro de combustível está entupido?",o:["Motor fazendo barulho","Dificuldade para dar partida, perda de potência e engasgos ao acelerar","Fumaça azul no escapamento","Consumo excessivo de óleo"],c:1,cat:"mecanica",ex:"Filtro de combustível entupido: restringe o fluxo, causando perda de potência e instabilidade."}
,{p:"A função das velas de aquecimento em motores diesel é:",o:["Igual às velas de ignição dos motores a gasolina","Pré-aquecer a câmara de combustão para facilitar a partida a frio","Controlar a injeção de combustível","Aumentar a temperatura do motor"],c:1,cat:"mecanica",ex:"Motores diesel não têm centelha. As velas de aquecimento aquecem o ar na câmara para facilitar a ignição."}
,{p:"O que é a 'pressão de inflação' correta do pneu?",o:["A pressão indicada na lateral do pneu (pressão máxima)","A pressão indicada na etiqueta do veículo (manual ou portal da tampa do combustível)","Sempre 32 PSI para todos os veículos","Não importa se dentro de ±5 PSI"],c:1,cat:"mecanica",ex:"Use a pressão da etiqueta do veículo (varia por modelo e carga). A lateral do pneu mostra a pressão MÁXIMA."}
,{p:"Em veículo com câmbio automático, o seletor 'P' (Park) serve para:",o:["Ligar o piloto automático","Travar mecanicamente a transmissão quando estacionado","Reduzir a marcha para subidas","Ativar a tração nas 4 rodas"],c:1,cat:"mecanica",ex:"'P' no câmbio automático: trava a transmissão mecanicamente. Sempre use com o freio de estacionamento."}
,{p:"Quando o pedal da embreagem fica esponjoso ou mole, indica:",o:["Funcionamento normal","Ar no sistema hidráulico de embreagem ou fluido baixo — verificar urgente","Embreagem muito nova","Problema no câmbio apenas"],c:1,cat:"mecanica",ex:"Pedal mole de embreagem = ar ou vazamento no sistema hidráulico. Pode falhar completamente em breve."}
,{p:"Qual a função dos amortecedores dianteiros nos freios?",o:["Não têm relação","Amortecedores em bom estado reduzem a distância de frenagem em até 20%","Apenas conforto","Controle de tração"],c:1,cat:"mecanica",ex:"Amortecedores gastos: pneu 'quica' ao frear, reduzindo o contato com o solo e aumentando a distância de parada."}
];
